// Test builders over the generated wire types: fill every required field inert, never cast
// through `unknown`.

import type {
  CurrentRound,
  DashboardCandidate,
  DashboardSample,
  LiveDashboardState,
  RoundResult,
  RoundSummary,
  RoundSummaryCandidate,
  ScoredCandidate,
} from "@/lib/types";

export function sampleRow(over: Partial<DashboardSample> = {}): DashboardSample {
  return {
    qi: 0,
    sample_id: null,
    status: "HIT",
    fitness: null,
    terminal_node: "",
    cached: false,
    time_s: null,
    cost_s: null,
    predicted: "",
    ground_truth: "",
    query: "",
    input_tokens: null,
    output_tokens: null,
    cache_read_tokens: null,
    ...over,
  };
}

export function currentRound(over: Partial<CurrentRound> = {}): CurrentRound {
  return {
    round: 0,
    active_node: null,
    candidates: [],
    nodes: {},
    pobb: { current_id: "", n_samples: 0, leader_prob: 0, posterior_width: 1, top: [] },
    // Null = the round has not elected yet.
    overlap: null,
    ...over,
  };
}

export function liveRow(over: Partial<DashboardCandidate> = {}): DashboardCandidate {
  return {
    label: "C1.1",
    candidate_id: null,
    run_id: null,
    accuracy: null,
    composite_fitness: null,
    scored_samples: 0,
    cached_samples: 0,
    input_tokens: null,
    output_tokens: null,
    cache_read_tokens: null,
    expected_samples: null,
    evaluators: {},
    changes_description: "",
    partial_reason: "",
    theta: null,
    theta_se: null,
    theta_caveat: null,
    mean_fitness_ci_lo: null,
    mean_fitness_ci_hi: null,
    matched_parent_accuracy: null,
    matched_parent_composite: null,
    matched_parent_lift: null,
    matched_parent_lift_ci_lo: null,
    matched_parent_lift_ci_hi: null,
    // "Nothing crowned yet": the election lands at the end of scoring, not at round close.
    is_winner: false,
    invalid: false,
    ...over,
  };
}

export function scored(over: Partial<ScoredCandidate> = {}): ScoredCandidate {
  return {
    candidate_id: "c",
    label: "C1.1",
    run_id: null,
    changes_description: "",
    accuracy: 0,
    composite_fitness: 0,
    total: 0,
    evaluators: {},
    sp_hash: "",
    pipeline_overlay: null,
    resolved_pipeline_params: null,
    prompt_fields: {},
    escalation_aborted: false,
    elimination_stopped: false,
    scored_samples: 0,
    expected_samples: 0,
    cached_samples: 0,
    input_tokens: null,
    output_tokens: null,
    cache_read_tokens: null,
    partial_reason: "",
    invalid: false,
    validation_failures: [],
    runtime_failures: [],
    elimination_context: {},
    degradation_context: {},
    matched_parent_accuracy: null,
    matched_parent_composite: null,
    matched_parent_lift: null,
    matched_parent_lift_ci_lo: null,
    matched_parent_lift_ci_hi: null,
    theta: null,
    theta_se: null,
    theta_caveat: null,
    mean_fitness_ci_lo: null,
    mean_fitness_ci_hi: null,
    ...over,
  };
}

export function roundDoc(over: Partial<RoundResult> = {}): RoundResult {
  return {
    round: 0,
    // `null` as a diagnostic replay writes, never 0, which is a real record.
    at_offset: null,
    label: "C0",
    accuracy: 0,
    composite_fitness: 0,
    total: 0,
    improved: false,
    // Never `false`, which asserts it measured cleanly and told nothing apart.
    separable: null,
    electable_count: 0,
    p_value: null,
    verdict_reason: null,
    degraded_samples: 0,
    not_attempted: 0,
    unscored: 0,
    deprecated: 0,
    escalation_signal: null,
    matched_parent_accuracy: null,
    matched_parent_composite: null,
    matched_parent_lift: null,
    matched_parent_lift_ci_lo: null,
    matched_parent_lift_ci_hi: null,
    ability: null,
    prompt_fields: {},
    pipeline_params: null,
    parent_accuracy: 0,
    results: [],
    all_candidate_results: {},
    parent_results: [],
    candidates_scored: 0,
    candidate_scores: [],
    evaluators: {},
    l1_yield: 1,
    l1_n_no_op: 0,
    l1_n_duplicate: 0,
    l1_n_repeat: 0,
    l1_parse_failure: null,
    diagnostics: null,
    critique: null,
    health: null,
    opt_sp: null,
    axis_memory_peaked: [],
    optimizer_prompt_hashes: {},
    status: "",
    overlap: null,
    overlap_results: {},
    round_id: "round_0",
    scoreboard: [],
    ...over,
  };
}

export function dash(over: Partial<LiveDashboardState> = {}): LiveDashboardState {
  return {
    campaign_id: "ds__000000",
    cycle_id: "cycle_0",
    session_id: "sess_0",
    // The pre-first-record offset the projection starts from.
    at_offset: -1,
    langfuse_trace_url: null,
    state: "init",
    state_since: "",
    // `declared_phase` is what the runner wrote, `run_phase` what the route derived; set both.
    declared_phase: "running",
    run_phase: "running",
    stop_reason: null,
    round: 0,
    candidate: "",
    patience: "",
    hearts: null,
    rounds: [],
    best: 0,
    current_acc: 0,
    ability_delta: null,
    ability_delta_per_usd: null,
    composite_fitness_formula: null,
    composite_fitness_weights: null,
    headline_metric: "accuracy",
    degraded_count: 0,
    error_count: 0,
    backend_retry_count: 0,
    recent_backend_warnings: [],
    recent_loop_warnings: [],
    total_queries_scored: 0,
    total_backend_calls: 0,
    current_query_payload: null,
    current_sample_id: null,
    open_sample_ids: [],
    declared_sample_order: [],
    sample_lookahead: 1,
    sample_lookahead_auto: false,
    sample_lookahead_discards: 0,
    in_flight: 0,
    lookahead_allowed: 0,
    lookahead_most: 0,
    lookahead_affordable: null,
    cell_reserve_usd: null,
    waiting_on: null,
    waiting_since: null,
    backpressure: null,
    max_cells_in_flight: 1,
    measured_unit: "sample",
    last_query_elapsed_s: 0,
    wallclock_serialized_at: null,
    n_variants: 0,
    sp_budget_round: 0,
    run_limits: null,
    spend: {
      backend: { used_usd: 0, input_tokens: 0, output_tokens: 0, reasoning_tokens: 0, cache_read_tokens: 0, cache_write_tokens: 0, rate_known: false, model: null, unpriced_tokens: 0, incurred_usd: 0, incurred_unpriced_tokens: 0 },
      loop: { used_usd: 0, input_tokens: 0, output_tokens: 0, reasoning_tokens: 0, cache_read_tokens: 0, cache_write_tokens: 0, rate_known: false, model: null, unpriced_tokens: 0, incurred_usd: 0, incurred_unpriced_tokens: 0 },
      judge: { used_usd: 0, input_tokens: 0, output_tokens: 0, reasoning_tokens: 0, cache_read_tokens: 0, cache_write_tokens: 0, rate_known: false, model: null, unpriced_tokens: 0, incurred_usd: 0, incurred_unpriced_tokens: 0 },
      diagnostic: { used_usd: 0, input_tokens: 0, output_tokens: 0, reasoning_tokens: 0, cache_read_tokens: 0, cache_write_tokens: 0, rate_known: false, model: null, unpriced_tokens: 0, incurred_usd: 0, incurred_unpriced_tokens: 0 },
      total_used_usd: 0,
      total_incurred_usd: 0,
      total_tokens_used: 0,
      unpriced_tokens: 0,
    },
    spend_by_round: {},
    backfill_log: [],
    current_round: currentRound(),
    error: null,
    ...over,
  };
}

// Mirrors `domain/results.py::candidate_label` (round 0 is `C0` for every arm). Only a fixture
// spells it: it stands in for a response, and production reads the label off the row.
export const servedLabel = (round: number, idx: number) =>
  round === 0 ? "C0" : `C${round}.${idx + 1}`;

export function summaryCandidate(
  over: Partial<RoundSummaryCandidate> = {},
): RoundSummaryCandidate {
  return {
    candidate_id: "c",
    label: "C1.1",
    run_id: null,
    accuracy: 0,
    composite_fitness: 0,
    scored_samples: 0,
    expected_samples: 0,
    cached_samples: 0,
    input_tokens: null,
    output_tokens: null,
    cache_read_tokens: null,
    is_winner: false,
    is_leading: false,
    invalid: false,
    evaluators: {},
    changes_description: "",
    partial_reason: "",
    theta: null,
    theta_se: null,
    theta_caveat: null,
    mean_fitness_ci_lo: null,
    mean_fitness_ci_hi: null,
    matched_parent_accuracy: null,
    matched_parent_composite: null,
    matched_parent_lift: null,
    matched_parent_lift_ci_lo: null,
    matched_parent_lift_ci_hi: null,
    ...over,
  };
}

export function summaryRound(over: Partial<RoundSummary> = {}): RoundSummary {
  return {
    round: 0,
    accuracy: 0,
    composite_fitness: 0,
    ability: null,
    improved: null,
    electable_count: null,
    verdict_reason: null,
    separable: null,
    candidates: [],
    selection: [],
    health: null,
    overlap: null,
    panel_precision: null,
    ...over,
  };
}
