"""CAPO's working state between rounds: the population its selector kept. Every round document
banks it whole, so a resume or a fork re-seats the population off the round it continues from."""

from __future__ import annotations

from typing import Literal

from promptpotter.domain.opt_search_point import OptSearchPoint
from promptpotter.domain.optimizer_state import RoundPayload

__all__ = ["CAPO_MANIFEST", "CapoRoundState"]

CapoManifest = Literal["capo"]
CAPO_MANIFEST: CapoManifest = "capo"


class CapoRoundState(RoundPayload, manifest=CAPO_MANIFEST):
    """CAPO's payload: the population its selector kept.

    The next round draws its parents from it and races it again beside their offspring."""

    # Empty on the origin's document: the initial population is generated by round 1.
    population: list[OptSearchPoint]
    # The longest initial prompt's scored length in characters, which CAPO's objective divides
    # the length term by (§4). ``None`` until round 1 generates that population.
    length_norm: int | None
