"""Per-round action trace recorder — flushes to ``campaigns/{cycle_id}/rounds/round_NNNN.json``."""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from promptpotter.infrastructure.store.base import write_json

logger = logging.getLogger(__name__)

__all__ = ["RoundRecorder"]


def _action_to_node_block(action: dict[str, Any]) -> dict[str, Any]:
    """Project an LLM action dict into the ``nodes[*]`` block shape.

    Input: the dict passed to ``add_action`` from ``pipeline.llm_call()``.
    Output: ``{input: {template_fields, variables}, output: {response},
    usage, model, duration_s, timestamp}``. Falls back to ``messages``
    when the caller didn't supply a ``template_fields`` decomposition.
    """
    input_block: dict[str, Any] = {}
    template_fields = action.get("template_fields")
    if template_fields is not None:
        input_block["template_fields"] = template_fields
    variables = action.get("variables")
    if variables is not None:
        input_block["variables"] = variables
    template_name = action.get("template_name")
    if template_name is not None:
        input_block["template_name"] = template_name
    # Fallback path: raw compiled messages when the call site didn't
    # provide a template decomposition.
    if not input_block and "messages" in action:
        input_block["messages"] = action["messages"]

    block: dict[str, Any] = {
        "input": input_block,
        "output": {"response": action.get("response")},
    }
    if "usage" in action:
        block["usage"] = action["usage"]
    if "model" in action:
        block["model"] = action["model"]
    if "config" in action:
        block["config"] = action["config"]
    if "duration_s" in action:
        block["duration_s"] = action["duration_s"]
    if "timestamp" in action:
        block["timestamp"] = action["timestamp"]
    return block


class RoundRecorder:
    """Accumulates node I/O within a round, writes ``round_NNNN.json`` on flush."""

    def __init__(self, rounds_dir: Path) -> None:
        self.rounds_dir = rounds_dir
        self._current_round: int = 0
        self._nodes: dict[str, dict[str, Any]] = {}
        self._l1_score: dict[str, Any] | None = None
        self._hitl: dict[str, Any] | None = None
        self._started_at: str = ""

    def begin_round(self, round_num: int) -> None:
        """Start recording a new round. Discards any pending node data."""
        if self._nodes or self._l1_score or self._hitl:
            logger.warning(
                "RoundRecorder: unflushed state from round %d discarded",
                self._current_round,
            )
        self._current_round = round_num
        self._nodes = {}
        self._l1_score = None
        self._hitl = None
        self._started_at = datetime.now(UTC).isoformat()

    def add_action(self, action: dict[str, Any]) -> None:
        """Record an LLM node call into the current round.

        Called by ``pipeline.llm_call()`` for every optimizer node. The
        action dict is reshaped into the ``{input, output, usage, ...}``
        block and keyed by node type (``l1_generate``, ``l1_critique``,
        ``l2_context``, ``l3_plan``). Re-entry on the same
        type overwrites — probes or retries naturally shadow the earlier
        call, matching the user's mental model ("what was the last thing
        node X did this round?").
        """
        action.setdefault("timestamp", datetime.now(UTC).isoformat())
        node_type = str(action.get("type") or "llm_call")
        self._nodes[node_type] = _action_to_node_block(action)

    def set_node(self, name: str, block: dict[str, Any]) -> None:
        """Deposit a prebuilt node block under ``name``.

        Used when a node's output is available but didn't flow through
        ``pipeline.llm_call()`` — e.g. ``l1_generate`` on a resumed round
        where candidates were loaded from ``candidates/round_NNNN.json``
        instead of generated by a fresh LLM call.
        """
        self._nodes[name] = block

    def set_l1_score(self, block: dict[str, Any]) -> None:
        """Deposit the scoring-phase block built by the session emitter."""
        self._l1_score = block

    def set_hitl(self, block: dict[str, Any]) -> None:
        """Deposit the HITL snapshot built by the session emitter."""
        self._hitl = block

    def snapshot_nodes(self) -> dict[str, dict[str, Any]]:
        """Return a copy of the current in-progress ``nodes`` dict.

        Used by the session emitter to mirror the LLM node I/O captured
        so far into ``dashboard.json::current_round`` while the round is
        still running. The scoring-phase block (``l1_score``) is *not*
        included — the emitter owns that data and composes it separately.
        """
        return dict(self._nodes)

    def flush(self) -> Path | None:
        """Write ``round_NNNN.json`` and reset. Returns the written path.

        Node ordering in the output: ``l1_generate``, ``l1_critique``,
        ``l1_score``, then any remaining (L2, L3, etc.) in insertion
        order. Round *outcome* (accuracy, decision, opt_sp) still lives
        in ``trials/trial_NNNN.json`` via ``_checkpoint_round`` — this
        file is not the place for that data.
        """
        if not self._nodes and self._l1_score is None and self._hitl is None:
            return None

        self.rounds_dir.mkdir(parents=True, exist_ok=True)

        nodes_ordered: dict[str, Any] = {}
        # Prefer a predictable reading order: L1 generate/critique first,
        # then scoring, then any escalation layers.
        for preferred in ("l1_generate", "l1_critique"):
            if preferred in self._nodes:
                nodes_ordered[preferred] = self._nodes[preferred]
        if self._l1_score is not None:
            nodes_ordered["l1_score"] = self._l1_score
        for key, block in self._nodes.items():
            if key not in nodes_ordered:
                nodes_ordered[key] = block

        path = self.rounds_dir / f"round_{self._current_round:04d}.json"
        payload: dict[str, Any] = {
            "round": self._current_round,
            "started_at": self._started_at,
            "finished_at": datetime.now(UTC).isoformat(),
            "nodes": nodes_ordered,
        }
        if self._hitl is not None:
            payload["hitl"] = self._hitl

        write_json(path, payload, default=str)
        logger.debug(
            "Round %d recorded: %d nodes → %s",
            self._current_round,
            len(nodes_ordered),
            path.name,
        )

        self._nodes = {}
        self._l1_score = None
        self._hitl = None
        return path
