// AUTOGENERATED by scripts/build_ts_types.py — do not hand-edit.
// Run `python scripts/build_ts_types.py` to regenerate from the Pydantic
// models in `promptpotter/` and commit the diff alongside any schema change.

/** A Rasch θ and the δ scale it was read on — meaningless apart, so they are one value. */
export interface AbilityReading {
  theta: number;
  se: number | null;
  ruler_id: string | null;
  ruler_n: number;
  ruler_span: number | null;
  round_span: number | null;
  calibration_model: '1PL' | '2PL' | null;
  caveat: 'cold_ruler' | 'flat_ruler' | 'collapsed_band' | 'floor_pinned' | null;
}

/** One candidate as `dashboard.json` serves it, in ANY round state — the live rows under */
export interface DashboardCandidate {
  label: string;
  candidate_id: string | null;
  accuracy: number | null;
  composite_fitness: number | null;
  invalid: boolean;
  scored_samples: number;
  cached_samples: number;
  expected_samples: number | null;
  evaluators: Record<string, number>;
  changes_description: string;
  partial_reason: string;
  theta: number | null;
  theta_se: number | null;
  theta_caveat: 'cold_ruler' | 'flat_ruler' | 'collapsed_band' | 'floor_pinned' | null;
  mean_fitness_ci_lo: number | null;
  mean_fitness_ci_hi: number | null;
  matched_parent_accuracy: number | null;
  matched_parent_composite: number | null;
  matched_parent_lift: number | null;
  matched_parent_lift_ci_lo: number | null;
  matched_parent_lift_ci_hi: number | null;
  is_winner: boolean;
}

/** One scored sample as `dashboard.json` serves it — the rule `DashboardCandidate` states, */
export interface DashboardSample {
  /** Iteration position within the candidate's walk — the #000 column. */
  qi: number;
  /** Dataset sample id, which diverges from qi once the hard-sample sorter drives
   * the order. Null where the row carries none. */
  sample_id: number | null;
  /** The grading verdict. */
  status: 'HIT' | 'MISS' | 'ERR';
  /** Pipeline node the row terminated at; the tape badges it. */
  terminal_node: string;
  /** Measurement reused from a prior identical searchpoint, not a fresh call. */
  cached: boolean;
  /** Recorded elapsed seconds. Null where the row never reached the pipeline —
   * distinct from a cached replay's real 0.0. */
  time_s: number | null;
  /** Prediction, trimmed for display. */
  predicted: string;
  /** Ground truth, trimmed for display. */
  ground_truth: string;
  /** Query, trimmed for display. */
  query: string;
  input_tokens: number | null;
  output_tokens: number | null;
}

/** A `DashboardCandidate` on a CLOSED round — `dashboard.json::rounds[].candidates`. */
export interface RoundSummaryCandidate {
  label: string;
  candidate_id: string;
  accuracy: number;
  composite_fitness: number;
  invalid: boolean;
  scored_samples: number;
  cached_samples: number;
  expected_samples: number;
  evaluators: Record<string, number>;
  changes_description: string;
  partial_reason: string;
  theta: number | null;
  theta_se: number | null;
  theta_caveat: 'cold_ruler' | 'flat_ruler' | 'collapsed_band' | 'floor_pinned' | null;
  mean_fitness_ci_lo: number | null;
  mean_fitness_ci_hi: number | null;
  matched_parent_accuracy: number | null;
  matched_parent_composite: number | null;
  matched_parent_lift: number | null;
  matched_parent_lift_ci_lo: number | null;
  matched_parent_lift_ci_hi: number | null;
  is_winner: boolean;
}

/** Context-aware degradation verdict for a round (origin included), computed */
export interface DegradationHealth {
  grade: 'healthy' | 'degraded' | 'critical';
  cause: 'origin_unmeasured' | 'origin_incomplete' | 'backend_unreachable' | 'structural' | 'unscoreable' | 'holed' | 'evidence_starved' | 'structural_untested' | 'persistent' | 'degraded' | null;
  samples: number;
  structural_count: number;
  transient_count: number;
  no_result_count: number;
  hole_count: number;
  answer_modal_share: number | null;
  degraded_rate: number;
  consecutive_degraded_rounds: number;
  prior_clean_rounds: number;
  dominant_node: string | null;
  node_failure_rates: Record<string, number>;
  node_warnings: Record<string, string[]>;
  suggested_action: string | null;
}

/** How sharply each cell was measured, against how far apart the cells landed — the two bars */
export interface PanelPrecision {
  estimation_sd: number;
  observed_sd: number;
  n_cells: number;
}

/** One parent, read on the round's overlap set. */
export interface OverlapMember {
  round: number;
  candidate_id: string;
  label: string;
  accuracy: number;
  total: number;
}

/** The cells EVERY parent has answered, and each one's rate over them. */
export interface OverlapReading {
  sample_ids: number[];
  members: OverlapMember[];
  measured: number;
}

/** Display row for `dashboard.json::rounds[]` — webapp's completed-round source. */
export interface RoundSummary {
  round: number;
  accuracy: number;
  composite_fitness: number;
  ability: AbilityReading | null;
  improved: boolean | null;
  electable_count: number | null;
  verdict_reason: string | null;
  candidates: RoundSummaryCandidate[];
  selection: number[];
  health: DegradationHealth | null;
  overlap: OverlapReading | null;
  panel_precision: PanelPrecision | null;
}

/** One on-demand workspace-scope diagnostic run — the ``verify`` and ``noise-floor`` */
export interface DiagnosticRunRecord {
  ts: string;
  dataset: string;
  source_campaign: string;
  source_cycle: string;
  source_label: string;
  source_candidate_id: string;
  config_hash: string;
  samples_requested: number;
  samples_added: number;
  workspace_n: number;
  workspace_accuracy: number;
  workspace_composite: number;
  source_campaign_accuracy: number;
  source_campaign_composite: number;
  source_campaign_n: number;
  noise_floor_k: number | null;
  noise_floor_mean: number | null;
  noise_floor_ci_lo: number | null;
  noise_floor_ci_hi: number | null;
  noise_floor_raw: number[] | null;
}

/** L1-output parse-time invariant violation; drives synthetic-0 in ``score_search_point``. */
export interface ValidationFailure {
  /** The parameter path that failed, ``{node_name}.{param}`` (e.g.
   * ``llm_only.model``), or an axis on the generator's own output rather than
   * a pipeline param: ``l1_generate.output`` (parse/shape failures) or
   * ``variant`` (no-op / duplicate mutations). */
  axis: string;
  /** The offending value as rendered for the prompt; truncated to ≤300 chars for
   * raw LLM output. Always a string — original type is encoded into the
   * rendering when relevant. */
  value: string;
  /** The accept-set the validator checked against. Empty list when the failure is
   * mode-based (parse error, forbidden axis) rather than membership-based. */
  allowed: string[];
  /** Reason code that steers L2's healing direction. One of: ``forbidden_axis``
   * (operator-locked param touched), ``type_mismatch`` (wrong declared type),
   * ``not_in_available_models`` / ``not_in_param_allowed_values`` (value
   * outside schema enum), ``reproposes_known_failing_config`` (matches a
   * prior ``RuntimeFailure.observed_config`` row),
   * ``l1_provider_empty_response`` / ``optimizer_prompt_parse_failure`` /
   * ``optimizer_prompt_unexpected_type`` (generator-side failure),
   * ``steers_inner_stopping`` (an L4 override telling the inner loop when to
   * STOP rather than how to search — it edits the frame `mean_round_delta`
   * averages over instead of the search it measures), ``steers_across_seeds``
   * (an L4 override making an inner node reason over the seed panel, which
   * exists only one level up — the rule renders empty where it lands),
   * ``guts_inherited_contract`` (an L4 override replacing a long prompt field
   * with a fraction of its length, deleting contracts the parent carried in
   * plain prose), ``no_op_variant`` / ``duplicate_variant`` (invariant-
   * detect), ``hallucinated_node`` (named a node absent from the schema —
   * NON-fatal: the phantom edit is stripped, the candidate still scores;
   * routed as signal, not a synthetic-0). */
  reason: string;
}

/** Post-eval degradation evidence, per-candidate. */
export interface RuntimeFailure {
  /** Failure family: ``degradation`` (mid-eval DegradationCheck fired on warning-
   * rate) or ``scoring_error_abort`` (scoring raised mid-eval and the
   * candidate was retired). */
  source: string;
  /** ``{node_name}:{warning_type}`` of the most frequent warning across the
   * candidate's measurements; the prefix selects the node whose config is
   * captured in ``observed_config``. */
  dominant_warning: string;
  /** Tally of each ``{node}:{warning}`` seen, by occurrence count. */
  warning_types: Record<string, number>;
  /** Fraction of scored samples that emitted any pipeline warning. */
  degraded_rate: number;
  /** Sample count with at least one warning. */
  degraded_count: number;
  /** Sample count actually measured for the candidate. */
  total_scored: number;
  /** Snapshot of the failing node's effective config — the (param, value) tuples
   * the `l1_config_not_in_runtime_failures` validator scans on subsequent
   * rounds to reject re-proposals. */
  observed_config: Record<string, unknown>;
  /** Round number that first recorded this failure (dedup key component). */
  first_seen_round: number;
  /** Label of the originating candidate; informational, not a join key. */
  candidate_label: string;
  /** Who heals this runtime failure. Defaults to ``L1`` (a rate-based degradation
   * L1 retunes the node config around); a deterministic-for-config break
   * whose only fix is a locked surface (schema/model) is stamped ``OPERATOR``
   * so it escalates instead of churning in-loop. */
  owner: 'l1' | 'operator';
}

/** One candidate's L1 score report — the single shape for round-file scores. */
export interface ScoredCandidate {
  candidate_id: string;
  label: string;
  changes_description: string;
  accuracy: number;
  composite_fitness: number;
  total: number;
  evaluators: Record<string, number>;
  pipeline_params_override: Record<string, unknown> | null;
  resolved_pipeline_params: Record<string, unknown> | null;
  prompt_fields: Record<string, unknown>;
  escalation_aborted: boolean;
  elimination_stopped: boolean;
  scored_samples: number;
  expected_samples: number;
  cached_samples: number;
  partial_reason: string;
  invalid: boolean;
  validation_failures: ValidationFailure[];
  runtime_failures: RuntimeFailure[];
  elimination_context: unknown;
  degradation_context: unknown;
  matched_parent_accuracy: number | null;
  matched_parent_composite: number | null;
  matched_parent_lift: number | null;
  matched_parent_lift_ci_lo: number | null;
  matched_parent_lift_ci_hi: number | null;
  theta: number | null;
  theta_se: number | null;
  theta_caveat: 'cold_ruler' | 'flat_ruler' | 'collapsed_band' | 'floor_pinned' | null;
  mean_fitness_ci_lo: number | null;
  mean_fitness_ci_hi: number | null;
}

/** One rank-ordered row of ``RoundResult.scoreboard`` — the round file's display table. */
export interface ScoreboardRow {
  rank: number;
  candidate_id: string;
  changes_description: string;
  accuracy: number;
  composite_fitness: number;
  total: number;
  escalation_aborted: boolean;
  matched_parent_accuracy: number | null;
  matched_parent_composite: number | null;
  mean_fitness_ci_lo: number | null;
  mean_fitness_ci_hi: number | null;
  theta: number | null;
  theta_se: number | null;
  theta_caveat: 'cold_ruler' | 'flat_ruler' | 'collapsed_band' | 'floor_pinned' | null;
  matched_parent_lift: number | null;
  matched_parent_lift_ci_lo: number | null;
  matched_parent_lift_ci_hi: number | null;
  is_winner: boolean;
}

/** An input/output pair used as a few-shot demonstration. */
export interface FewShotExample {
  input: string;
  output: string;
  explanation: string | null;
}

/** Panel field + citation L1 declares to justify a mutation. */
export interface EvidenceGrounding {
  /** A citable panel named in the prompt, or stall_exploration. */
  field: string;
  /** Short string naming the panel entry cited. */
  citation: string;
}

/** Identity + provenance — set once at creation, never mutated. */
export interface IndividualLineage {
  id: string;
  parent_id: string | null;
  changes_description: string;
  /** 'origin' / 'l1_generate' / 'l2_context' / 'l3_plan' / 'fork_seed' /
   * 'campaign_origin'. */
  source: string;
  evidence_grounding: EvidenceGrounding | null;
}

/** Four wound streams + sticky L3 note; rendered by dispatch-hub injections. */
export interface WoundChannels {
  l3_note: string;
  validation_failures: ValidationFailure[];
  runtime_failures: RuntimeFailure[];
  l2_guard_breaches: unknown[];
  l3_guard_breaches: unknown[];
}

/** Per-slot list of placeholder names that the dispatch hub resolves */
export interface L1Layout {
  persona: string[];
  task_intent: string[];
  problem_description: string[];
  thinking_style: string[];
}

/** L2/L3-authored state that travels with the candidate. */
export interface L2L3Memory {
  /** Four wound streams (validation/runtime/l2-guard/l3-guard) + sticky L3 note.
   * Rendered by dispatch-hub injections; absorbed by L2 next round. */
  wounds: WoundChannels;
  /** L2-authored ordered list of injection slots that ``DispatchHub.fill`` walks to
   * compose the L1 optimizer prompt. L2's primary lever for changing what
   * evidence L1 sees. */
  l1_layout: L1Layout;
  /** Per-individual L1 optimizer prompt overrides keyed by the surface field name
   * (``persona``, ``instruction``, …). L2 writes here to nudge L1 without
   * rewriting the shared optimizer prompt. */
  l1_overrides: Record<string, unknown>;
  /** Persistent task-framing dict refined by ``l2_context`` and spliced around
   * ``problem_description`` at render time. Accumulative: each L2 fire merges
   * deltas rather than rewriting wholesale. */
  task_context: unknown;
}

/** Optimizer working state: prompt fields + lineage + L2/L3 memory. */
export interface OptSearchPoint {
  persona: string;
  task_intent: string;
  problem_description: string;
  instruction: string;
  thinking_style: string;
  answer_format: string;
  few_shot_examples: FewShotExample[];
  /** Strategic frame written by ``l3_plan`` and read by every layer next round;
   * persistent until the next L3 fire. Empty until L3 fires for the first
   * time. */
  plan: string;
  lineage: IndividualLineage;
  memory: L2L3Memory;
}

/** Per-round outcome — and the round document itself. */
export interface RoundResult {
  round: number;
  closed_at_offset: number | null;
  label: string;
  accuracy: number;
  composite_fitness: number;
  total: number;
  improved: boolean;
  p_value: number | null;
  verdict_reason: string | null;
  degraded_samples: number;
  deprecated: number;
  escalation_signal: unknown | null;
  matched_parent_accuracy: number | null;
  matched_parent_composite: number | null;
  matched_parent_lift: number | null;
  matched_parent_lift_ci_lo: number | null;
  matched_parent_lift_ci_hi: number | null;
  separable: boolean | null;
  ability: AbilityReading | null;
  prompt_fields: Record<string, unknown>;
  pipeline_params: Record<string, unknown> | null;
  parent_accuracy: number;
  results: Record<string, unknown>[];
  all_candidate_results: Record<string, Record<string, unknown>[]>;
  candidates_scored: number;
  electable_count: number;
  candidate_scores: ScoredCandidate[];
  evaluators: Record<string, number>;
  l1_yield: number;
  l1_parse_failure: string | null;
  overlap: OverlapReading | null;
  overlap_results: Record<string, unknown>[];
  diagnostics: unknown | null;
  critique: unknown | null;
  health: DegradationHealth | null;
  opt_sp: OptSearchPoint | null;
  axis_memory_peaked: string[];
  optimizer_prompt_hashes: Record<string, string>;
  status: string;
  round_id: string;
  /** Variants whose mutation was empty against the parent. */
  l1_n_no_op: number;
  /** Variants sig-equal to a sibling in the SAME population. */
  l1_n_duplicate: number;
  /** Variants re-proposing an idea an EARLIER round measured and lost. */
  l1_n_repeat: number;
  /** Rank-ordered display table — the crown first, then θ, then composite.
   * Derived, never stored: it cannot drift from `candidate_scores` the way a
   * hand-built twin could. On a warm round rank 1 IS the winner, by
   * construction; on a cold one no row carries a θ and the order falls back
   * to the composite it always had. */
  scoreboard: ScoreboardRow[];
}

/** One spend sub-bucket (backend or optimizer-loop). Mutated only by */
export interface SpendBucket {
  used_usd: number;
  input_tokens: number;
  output_tokens: number;
  reasoning_tokens: number;
  cache_read_tokens: number;
  cache_write_tokens: number;
  rate_known: boolean;
  model: string | null;
  unpriced_tokens: number;
  incurred_usd: number;
  incurred_unpriced_tokens: number;
}

/** A cycle's spend: the two buckets, and the totals every consumer reads off them. */
export interface SpendRollup {
  backend: SpendBucket;
  loop: SpendBucket;
  total_used_usd: number;
  total_incurred_usd: number;
  total_tokens_used: number;
  unpriced_tokens: number;
}

/** One entry in ``recent_backend_warnings`` — backend transport retry / 429 / 5xx surface. */
export interface BackendWarning {
  ts: string;
  kind: string;
  attempt: number | null;
  max_attempts: number | null;
  wait_s: number | null;
  error_class: string | null;
  status_code: number | null;
  final: boolean;
  query: string | null;
}

/** One entry in ``recent_loop_warnings`` — an optimizer-loop degradation the */
export interface LoopWarning {
  ts: string;
  kind: string;
  severity: string;
  message: string;
  round: number | null;
  detail: Record<string, unknown>;
}

/** ``dashboard.json::error`` — structured crash summary written by */
export interface DashboardError {
  kind: string;
  message: string;
  stop_reason: string;
}

/** ``state.run_limits`` — the cycle's run-limit ceilings, stamped at WIRING off the effective */
export interface RunLimits {
  max_rounds: number | null;
  l1_patience: number;
  l2_patience: number | null;
  l3_patience: number | null;
  pobb_epsilon: number;
  spend_budget_usd: number | null;
  token_budget: number | null;
  lives_cap: number | null;
}

/** ``state.in_flight`` — the optimizer LLM call currently in progress. */
export interface InFlightCall {
  call_id: string;
  node: string;
  model: string | null;
  round: number | null;
  candidate_idx: number | null;
  started_at_ms: number;
}

/** One paired-PoBB backfill event appended by ``LiveDashboardView._append_backfill``. */
export interface BackfillLogEntry {
  round: number;
  candidate_idx: number;
  candidate_total: number;
  sample_id: number;
  prior_ids: string[];
}

/** ``current_round.pobb`` — round-wide elimination telemetry, rebuilt every persist. */
export interface PobbBlock {
  current_id: string;
  n_samples: number;
  leader_prob: number;
  posterior_width: number;
  top: Record<string, unknown>[];
}

/** ``dashboard.json::current_round`` — the round in flight, rebuilt whole on every persist. */
export interface CurrentRound {
  round: number;
  active_node: string | null;
  candidates: DashboardCandidate[];
  nodes: Record<string, Record<string, unknown>>;
  pobb: PobbBlock;
  overlap: OverlapReading | null;
}

/** ``dashboard.json`` — operator-facing snapshot, polled by the webapp. */
export interface LiveDashboardState {
  campaign_id: string;
  cycle_id: string;
  session_id: string;
  at_offset: number;
  langfuse_trace_url: string | null;
  state: 'init' | 'origin' | 'scoring' | 'between_samples' | 'between_candidates' | 'l1_generate' | 'l2_refining' | 'l3_replanning' | 'escalation' | 'stopped';
  state_since: string;
  declared_phase: 'checkin' | 'running' | 'paused' | 'gate' | 'detached' | 'terminal';
  run_phase: 'checkin' | 'running' | 'paused' | 'gate' | 'detached' | 'terminal';
  stop_reason: string | null;
  round: number;
  candidate: string;
  query: string;
  patience: string;
  hearts: number | null;
  rounds: RoundSummary[];
  best: number | null;
  current_acc: number | null;
  ability_delta: number | null;
  composite_fitness_formula: string | null;
  composite_fitness_weights: Record<string, number> | null;
  headline_metric: 'accuracy' | 'composite' | 'ability';
  degraded_count: number;
  error_count: number;
  backend_retry_count: number;
  recent_backend_warnings: BackendWarning[];
  recent_loop_warnings: LoopWarning[];
  total_queries_scored: number;
  total_backend_calls: number;
  current_query_payload: string | null;
  current_sample_id: number | null;
  open_sample_ids: number[];
  declared_sample_order: number[];
  sample_lookahead: number;
  sample_lookahead_discards: number;
  sample_lookahead_armed: number;
  max_cells_in_flight: number;
  concurrency_arming: 'round' | 'batch';
  measured_unit: 'sample' | 'cell';
  last_query_elapsed_s: number | null;
  wallclock_serialized_at: string | null;
  n_variants: number;
  sp_budget_ttest: number;
  run_limits: RunLimits | null;
  spend: SpendRollup;
  in_flight: InFlightCall | null;
  backfill_log: BackfillLogEntry[];
  current_round: CurrentRound;
  error: DashboardError | null;
}

export interface DatasetItem {
  sample_id: number;
  query: string;
  ground_truth: string;
  task: string | null;
  /** 1-based position in the served hard-sample ranking under this response's
   * `order`. THE ordering — a client renders rows in it and never re-derives
   * one, since an ordering is a score and a locally-sorted one silently
   * answers a different question in the same slot. Rows measured in this
   * scope rank first; the rest trail. */
  hard_sample_rank: number;
  /** Times this sample has been tried. ``null`` where the row is not in this
   * scope's Rasch artifact at all — the same absence its `delta` / `delta_se`
   * / `p_hat` neighbours already report, and not a fit that observed it zero
   * times. */
  n_obs: number | null;
  /** Queue-mechanism's blended objective on this sample for a brand-new candidate
   * (prior N(0, sigma_theta**2)) vs the best fitted candidate. The live
   * adaptive queue mechanism re-evaluates per step. None when unmeasured. */
  pick_score: number | null;
  /** Rasch difficulty delta_s (higher = harder). None when unmeasured. */
  delta: number | null;
  /** SE of delta_s (large = barely measured). None when unmeasured. */
  delta_se: number | null;
  /** Marginal hit prob the seed-centred decision-IG reads — see
   * ``adaptive_queue_mechanism.marginal_hit_probability``. Near 0.5 =
   * contested at seed; near 0/1 = predictable. None when unmeasured. */
  p_hat: number | null;
}

export interface DatasetPreviewResponse {
  name: string;
  row_count: number;
  /** Declared held-out test fold size (not materialized). The training-bank size is
   * `row_count` above — the bank IS the preview, so a second field restated
   * it. */
  split_test: number | null;
  /** The key `items` are ranked by — the request's `order` when it named one, else
   * the dataset's `CampaignConfig.hard_sample_order`. Echoed so a client that
   * sent no override can label what it is showing without guessing the
   * default. */
  order: 'info_gain' | 'difficulty';
  items: DatasetItem[];
}

export interface MeasurementDot {
  /** Opaque ordinal for lex sort + uniqueness (encodes ts/run/idx or round/cand). */
  ord: string;
  /** Graded per-sample score in [0,1] under the active scorer. Binary scorers emit
   * exactly 0.0 or 1.0; render a shade, not a HIT/MISS boolean. */
  fitness: number;
  /** Short human label, e.g. 'R3 cand 2'. */
  label: string;
}

export interface SampleSeries {
  sample_id: number;
  measurements: MeasurementDot[];
  /** How many of THIS series' measurements maxed out the active scorer
   * (`domain.scoring.is_hit`, the one definition of that threshold). Served
   * rather than counted client-side so the tally and the dots it summarises
   * cannot disagree — and so a graded scorer, whose ceiling is unreachable,
   * reports 0 against a mean that is not 0. */
  n_hits: number;
  /** Mean graded fitness over this series; `None` when it holds no measurement. The
   * rate to read on a graded scorer, where `n_hits` is structurally 0. */
  mean_fitness: number | null;
}

export interface MeasurementSeriesResponse {
  name: string;
  scope: 'cycle' | 'campaign' | 'dataset';
  /** The key `items` are ranked by, resolved exactly as `/preview`'s. Echoed on
   * BOTH responses because they are one page read twice: a client holding
   * only one of them would otherwise have to name the order from the other,
   * or guess the default. */
  order: 'info_gain' | 'difficulty';
  items: SampleSeries[];
  /** Measurements across every series in `items` — the denominator of the roster's
   * headline, served so the reader adds nothing up. */
  total_measurements: number;
  /** `SampleSeries.n_hits` summed across `items`. Structurally 0 on a graded
   * scorer; read `mean_fitness` there. */
  total_hits: number;
  /** Mean graded fitness across every measurement in `items`; `None` when the scope
   * holds none. The headline rate on any scorer, graded or binary. */
  mean_fitness: number | null;
}

/** One param a node carries — the COMPLETE per-node list, which is what lets */
export interface NodeConfigParam {
  key: string;
  value: unknown;
  kind: string;
  options: string[];
  description: string;
  optimizer_locked: boolean;
  optimizer_tunable: boolean;
}

/** Resolved output schema for a TARGET pipeline node — the structured output the */
export interface NodeOutputSchema {
  fields: string[];
  field_descriptions: Record<string, string>;
  json_schema: Record<string, unknown>;
}

/** One node's place in the flow, as a tier and a rank rather than as pixels. */
export interface PipelineViewNode {
  id: string;
  label: string;
  kind: string;
  tier: number;
  rank: number;
}

export interface PipelineViewEdge {
  from: string;
  to: string;
  kind: string;
}

/** The webapp-facing graph projection, derived from a manifest's nodes and pipelines. */
export interface PipelineView {
  nodes: PipelineViewNode[];
  edges: PipelineViewEdge[];
}

/** Which node of THIS pipeline runs another whole pipeline, and whose. Both halves are */
export interface NestedPipelineRef {
  /** Node id in this pipeline whose measurement runs `dataset`. */
  node: string;
  /** Slug of the pipeline that node runs; fetch it the same way. */
  dataset: string;
}

/** Target pipeline view for a dataset overlay. `view` drives the webapp chat-pane hero; */
export interface DatasetPipelineResponse {
  name: string;
  connector: string;
  backend_type: string | null;
  pipeline: Record<string, unknown>;
  view: PipelineView | null;
  node_config_schema: Record<string, NodeConfigParam[]>;
  node_output_schema: Record<string, NodeOutputSchema | null>;
  nests: NestedPipelineRef | null;
}

export interface ActiveSessionResponse {
  /** Tenant the pointer belongs to — the caller's own, always known */
  tenant_id: string;
  /** Active session id; null when no session is active. */
  session_id: string | null;
  /** Active campaign id (pinned by the webapp); null when no session is active. */
  campaign_id: string | null;
  /** Active cycle id within the campaign; null when no session is active. */
  cycle_id: string | null;
}

/** The outer work-item an L4 inner cycle was spawned to measure. */
export interface SpawnedBy {
  /** The outer cycle that owns this inner sandbox */
  outer_cycle_id: string;
  /** The outer CAMPAIGN that owns this inner sandbox. Required alongside the cycle
   * because a `cycle_id` is content-addressed on its origin and so is shared
   * by every campaign minted from that origin — the pair is the identity,
   * either half alone is not, and a null here is why two pooled sandboxes on
   * disk could not be attributed after the fact. */
  outer_campaign_id: string;
  /** Outer round; 0 is the origin (C0). Null when the spawn came from outside any
   * round (the noise-floor diagnostic). */
  round: number | null;
  /** Position in the outer round's population; null for the origin. */
  candidate_idx: number | null;
  /** The outer candidate's `OptSearchPoint.lineage.id` — stable across rounds; null
   * for the origin. */
  candidate_id: string | null;
  /** Canonical label (`C0` for the origin, else `C{round}.{idx+1}`) — the same
   * string the round file and console use. */
  candidate_label: string | null;
  /** The panel cell this run measured — the outer query, e.g.
   * `justlogic-d234/seed-0` (`inner_tasks.yaml::tasks[].id`). The candidate
   * fields do NOT identify a run: every task runs for every candidate, so one
   * candidate's spawns are as many as the panel has cells and are told apart
   * only by this. */
  task: string;
}

export interface CycleListEntry {
  /** Campaign the cycle belongs to */
  campaign_id: string;
  cycle_id: string;
  parent_session_id: string;
  /** Immediate parent for siblings (forks/sweeps/diag); null for roots. Sidebar
   * uses this to nest siblings. */
  parent_cycle_id: string | null;
  dataset_name: string;
  backend_id: string;
  mint_kind: 'session' | 'divergent_resume' | 'user_fork' | 'auto_rebase';
  is_root: boolean;
  status: string;
  /** The cycle_id that took this cycle's line, set on the LEFT-BEHIND side of a
   * supersede cut. This is the successor pointer — follow it to find which
   * cycle answers for the campaign; it is a fact of its own precisely so it
   * survives on a parent that had already stopped for its own reason, which
   * `status` cannot express. Null on a root, an offshoot, and any cycle still
   * holding the line. */
  superseded_by: string | null;
  /** The single run-state value (RunPhase). Computed once by derive_run_phase from
   * lifecycle + control flags + freshness; every picker dot and badge reads
   * this, none re-derive it. 'checkin' wins first (the campaign hasn't run);
   * 'terminal' pairs with `status` for the reason label. */
  run_phase: 'checkin' | 'running' | 'paused' | 'gate' | 'detached' | 'terminal';
  best_accuracy: number | null;
  /** Round 0's accuracy — the origin's measurement, derived from rounds[] (no
   * stored copy). Null until round 0 lands. */
  origin_accuracy: number | null;
  n_rounds: number;
  created_at: string;
  updated_at: string;
  /** True once an operator manually intervened (e.g. skip-searchpoint); the cycle
   * is babysat and no longer purely reproducible. Drives the 'babysat' badge;
   * orthogonal to run_phase. */
  human_intervened: boolean;
  /** Which outer work-item asked for this cycle, when it is an L4 inner
   * measurement; null for an ordinary campaign, which is the only reason it
   * is null. Lets the sidebar name an inner run by the candidate that
   * produced it instead of by launch order. */
  spawned_by: SpawnedBy | null;
}

export interface CyclesResponse {
  tenant_id: string;
  /** Active campaign per active_session.json; null when no session is active. */
  active_campaign_id: string | null;
  /** Active cycle per active_session.json; null when no session is active. */
  active_cycle_id: string | null;
  cycles: CycleListEntry[];
}

/** The 202 response shape declared in ``m12-api-openapi.yaml``. */
export interface CommandAcceptedBody {
  /** Stable id of the appended `CommandRecord`. */
  command_id: string;
  /** Echo of the request's `Idempotency-Key`. */
  correlation_id: string;
  /** Offset at which the `CommandRecord` was appended. */
  ledger_sequence: number;
}

export interface CampaignSummary {
  /** Campaign id ({dataset}__{rand6}) — one RUN of an origin */
  campaign_id: string;
  /** Dataset this campaign optimizes */
  dataset_name: string;
  /** Operator-supplied campaign label */
  label: string;
  /** ISO 8601 creation timestamp */
  created_at: string;
  /** The campaign's root cycle id — `cycle_<root_content_hash>`, so it IS the
   * campaign's ORIGIN identity. Campaigns on one declaration share it and
   * differ only in the random `campaign_id` suffix, which is what makes them
   * separate RUNS of that origin; the sidebar groups the forest by this key. */
  root_cycle_id: string;
  /** Backend this campaign optimizes against */
  backend_id: string;
  /** Connector KIND of the campaign's dataset ('termnorm' / 'promptpotter' / …),
   * read off `{dataset}/pipeline.yaml::backend_type`. The webapp's ONE test
   * for a self-optimizing (L4) campaign — it renders the 'inner loops'
   * disclosure and the pp-self panel variants on it. Empty when the dataset
   * config is gone (a campaign outlives its dataset dir); callers treat empty
   * as 'not self-optimizing'. */
  backend_type: string;
  /** UserId of the operator who minted the campaign */
  owner_user_id: string;
  /** Operator visibility intent: 'active' (default sidebar), 'archived' (hidden),
   * 'deleted' (soft-marked, data retained) */
  lifecycle_status: string;
  /** ISO 8601 timestamp of last lifecycle transition */
  lifecycle_changed_at: string;
  /** Optional operator-supplied reason for the last lifecycle transition */
  lifecycle_reason: string;
}

export interface CampaignListResponse {
  /** List of campaign summaries */
  campaigns: CampaignSummary[];
  /** Total number of campaigns */
  total: number;
}

/** Where one occurrence of an edit was measured on disk. */
export interface EffectProvenance {
  campaign_id: string;
  cycle_id: string;
  round: number;
  candidate_id: string;
}

/** How far apart the ranked edits actually are — the SD of ``anchor_effect`` across them. */
export interface EditSpread {
  edit_effect_sd: number | null;
  n_edits: number;
}

/** One unique candidate state — a ``pipeline_params_override`` — aggregated across every */
export interface RankedEdit {
  state_hash: string;
  label: string;
  provenance: EffectProvenance[];
  anchor_effect: number;
  ci_lo: number | null;
  ci_hi: number | null;
  n_cells: number;
  n_measurements: number;
}

/** Whether the selection's ABSOLUTE levels are one quantity, and WHY — two ways to fail and a */
export interface Comparability {
  verdict: boolean | null;
  reason: 'one_ruler' | 'rulers_differ' | 'ruler_unstamped' | 'datasets_differ';
  datasets: string[];
  n_rulers: number;
  note: string;
}

/** One arm — a CONFIGURATION identity, which is what the word keeps meaning here — that ran */
export interface ArmReplicate {
  arm_id: string;
  campaign_ids: string[];
  level_spread: number;
  n_instruments: number;
}

/** The additive cell + subject decomposition over the cells every subject measured. */
export interface EvidenceVariance {
  cell_effect_sd: number;
  subject_effect_sd: number;
  residual_sd: number;
  null_subject_scatter: number;
  subject_sd_below_noise: boolean;
  n_cells: number;
  n_subjects: number;
}

/** What this instrument can and cannot resolve, at the width it is currently run. */
export interface EvidencePower {
  paired_se: number;
  min_detectable_effect: number;
  largest_subject_gap: number;
  cells_per_subject: number;
  cells_for_largest_gap: number | null;
  exact_p_floor: number;
  cells_for_corrected_verdict: number;
}

/** Run order against outcome. A one-at-a-time comparison confounds the subject with WHEN it */
export interface OrderConfound {
  level_vs_order: number | null;
  spend_vs_order: number | null;
  n_subjects: number;
  order_confounded: boolean;
}

/** One pickable metric. Served rather than restated in the browser, so a label and a unit have */
export interface MetricSpec {
  key: string;
  label: string;
  expression: string;
  unit: 'level' | 'delta' | 'seconds' | 'usd' | 'tokens' | 'rank' | 'rounds' | 'composed';
  higher_is_better: boolean | null;
  description: string;
  /** What to CALL this metric's axis: the label, plus the unit only where the unit
   * names something the reader does not already have. SERVED, so neither
   * surface hand-writes the "unnamed" set below to derive it. */
  axis_label: string;
}

/** The mask this channel is read under, echoed back. Served rather than left implicit in the */
export interface SubjectMask {
  lens: string | null;
  samples: number[] | null;
}

/** What the mask did to this branch: how far it agrees with the record, and the round it stops. */
export interface ScenarioReading {
  recorded_winner_id: string | null;
  scenario_winner_id: string | null;
  winner_changed: boolean;
  first_divergent_round: number | null;
  invariant_rounds: number;
  total_rounds: number;
  n_samples_scored: number;
  note: string;
}

/** One step of the branch standing behind a subject — the winner chain from the origin up to */
export interface TrajectoryPoint {
  candidate_id: string;
  round: number;
  label: string;
  value: number | null;
  ci_lo: number | null;
  ci_hi: number | null;
  n_cells: number;
}

/** One subject, read under the selected metric — its identity, its per-cell values and the one */
export interface SubjectReading {
  key: string;
  kind: 'campaign' | 'course' | 'candidate';
  inside: CycleHop[];
  campaign_id: string;
  cycle_id: string;
  candidate_id: string;
  label: string;
  dataset_name: string;
  created_at: string;
  comparable: boolean | null;
  comparable_note: string;
  mask: SubjectMask | null;
  scenario: ScenarioReading | null;
  trajectory: TrajectoryPoint[] | null;
  config: Record<string, string> | null;
  arm_id: string | null;
  instrument_id: string | null;
  ability: AbilityReading | null;
  round: number;
  cycle_spend_usd: number | null;
  cycle_rounds_scored: number;
  spend_to_round: Record<string, number>;
  values: Record<string, number>;
  value: number | null;
  ci_lo: number | null;
  ci_hi: number | null;
  n_cells: number;
  unscorable_cells: string[];
}

/** One unordered pair, blocked on the cells BOTH subjects scored — pairing removes cell */
export interface PairwiseComparison {
  subject_a: string;
  subject_b: string;
  median_shift: number;
  ci_lo: number | null;
  ci_hi: number | null;
  p_value: number | null;
  p_adjusted: number | null;
  n_cells: number;
}

/** The selection read under ONE metric, echoed back with the vocabulary it was chosen from — a */
export interface MetricReading {
  spec: MetricSpec;
  catalogue: MetricSpec[];
  namespace: string[];
  scored_cells: string[];
  covered_cells: string[];
  pairwise: PairwiseComparison[];
  n_tests: number;
}

/** The whole read for one selection of subjects — recomputed on every fetch. */
export interface Evidence {
  generated_at: string;
  subjects: SubjectReading[];
  comparability: Comparability;
  metric: MetricReading;
  unread_subjects: string[];
  replicates: ArmReplicate[];
  variance: EvidenceVariance | null;
  power: EvidencePower | null;
  order_confound: OrderConfound | null;
  ranking_computed: boolean;
  edits: RankedEdit[];
  spread: EditSpread;
}

export interface FileEntry {
  /** Path relative to the scope root, forward slashes */
  path: string;
  /** Which root the path is under */
  scope: 'cycle' | 'campaign';
  /** File size in bytes */
  size: number;
  /** ISO 8601 UTC modification time */
  mtime: string;
}

export interface FilesResponse {
  campaign_id: string;
  cycle_id: string;
  entries: FileEntry[];
}

export interface FileContentResponse {
  campaign_id: string;
  cycle_id: string;
  scope: 'cycle' | 'campaign';
  path: string;
  size: number;
  mtime: string;
  content_type: 'json' | 'markdown' | 'log' | 'text' | 'binary';
  /** UTF-8 text content; None when binary or oversized */
  content: string | null;
}

/** One ``(campaign, cycle)`` step of a :data:`CyclePath`. */
export interface CycleHop {
  campaign_id: string;
  cycle_id: string;
}

/** Where an alternative criterion would have elected someone else. Rides the node it */
export interface LineageDivergence {
  /** The candidate the masked criterion would have elected instead (measured, so
   * nameable); null when the round would simply have held on origin. */
  alternative_candidate_id: string | null;
}

/** One node of the served tree. The same shape at every depth — that is the point. */
export interface LineageNode {
  /** course | candidate — they strictly alternate */
  kind: 'course' | 'candidate';
  /** Course: the cycle_id. Candidate: the searchpoint id minted at L1/origin. */
  id: string;
  /** The candidate this node descends from; null only at the true root. A course
   * carries the same edge its own C0 carries. */
  parent_id: string | null;
  /** `C{round}.{n}` on the campaign's ONE timeline: this course's own candidates
   * keep their minted label; an attempt a fork contributed takes the next
   * free index of its round, by mint time — UNLESS the cut superseded, where
   * it keeps its own label because it replaced that position rather than
   * joining it, and the candidate it replaced carries `superseded_by`. So one
   * label can appear twice in a round: at most once LIVE, the other retired. */
  label: string;
  /** This candidate's label in the course that MINTED it. Equal to `label` for a
   * candidate this course minted itself; a fork-contributed attempt keeps the
   * fork's private `C{round}.{n}` here while `label` carries its renumbered
   * position on this course's timeline. JOIN ON THIS, never on
   * `candidate_id`, when matching a node against a per-cycle projection:
   * `dashboard.json` is per-cycle and speaks the minting course's private
   * counter, while `candidate_id` is re-minted per run (see `_round_facts`),
   * so an id join silently misses. */
  course_label: string;
  /** THE address, root → leaf: the course this node belongs to. A candidate a fork
   * contributed carries the FORK's path, so selecting it re-roots onto that
   * fork. */
  path: CycleHop[];
  children: LineageNode[];
  /** Column hint. Candidates only. */
  round: number | null;
  accuracy: number | null;
  composite_fitness: number | null;
  /** Candidate: minted | measured | invalid — never 'winner' (that rides
   * `is_winner`). `invalid` was rejected before it cost a sample, so it
   * carries no accuracy: its stored 0.0 is synthetic and reads as getting
   * every answer wrong. Course: `index.json::status`, the same StopReason
   * value `/cycles` serves under this same name. Not `dashboard.json::state`,
   * which names the fine-grained ACTIVITY phase — a different axis, and one
   * word may not serve both. */
  status: string;
  /** This candidate's ROUND has held its election. The complement `is_winner`
   * cannot supply: a round that HELD crowned nobody, so every bar in it reads
   * `is_winner: false` exactly as a round still scoring does — and only this
   * says whether an uncrowned bar lost or has not been judged yet. False on a
   * course, which is not a round, and on a round halted before it stood (a
   * holed panel). */
  election_held: boolean;
  /** Elected this round. Stamped at the ELECTION, which is the last thing scoring
   * does — so it lands a whole `l1_critique` call before the round closes,
   * and a round still running its optimizer calls already reports its winner.
   * False where no election has been held (still scoring, or halted on a
   * holed panel) and on a round that held: those two are told apart by the
   * election record, not by this flag. */
  is_winner: boolean;
  /** Difficulty-adjusted Rasch ability the election ranked on — what explains a
   * lower-accuracy winner. Null outside the round's election fit. */
  theta: number | null;
  theta_se: number | null;
  /** Why the theta above is not this arm's ability. Only ever `floor_pinned` — the
   * arm scored 0.0 on every cell it answered, so the fit had no response to
   * separate ability from the prior and every lift against it reads 0.000.
   * The other three caveats are properties of the round's scale and ride the
   * round's own reading. */
  theta_caveat: 'cold_ruler' | 'flat_ruler' | 'collapsed_band' | 'floor_pinned' | null;
  /** The candidate's stored evaluator namespace — the measurement a `score:` lens
   * re-scores against. */
  evaluators: Record<string, number>;
  mean_fitness_ci_lo: number | null;
  mean_fitness_ci_hi: number | null;
  /** The candidate's blocked lift over the floor it was JUDGED against — the origin
   * restricted to the cells this candidate actually measured — with its 95%
   * interval. The election's own verdict, and the only comparable answer to
   * 'by how much': under `per_round_resubset` a bare difference of two
   * accuracies is the luckiest draw minus the fullest one. An interval
   * spanning 0 means the round could not separate this candidate from its
   * parent. `None` below two shared cells, outside the election fit, and on
   * any round that has not elected yet. */
  matched_parent_lift: number | null;
  matched_parent_lift_ci_lo: number | null;
  matched_parent_lift_ci_hi: number | null;
  scored_samples: number | null;
  expected_samples: number | null;
  /** Of `scored_samples`, how many were replayed from the MeasurementArchive rather
   * than measured. `None` on a course and on any candidate never measured. */
  cached_samples: number | null;
  /** This candidate's fitness under the request's `score:` lens, re-scored server-
   * side from its stored evaluator namespace. Null without a lens, or when
   * the namespace can't satisfy the formula. */
  lens_value: number | null;
  /** 1-based position by `composite_fitness` descending among THIS node's siblings
   * — the bars one chart draws. Null where the value is. An ordering is a
   * score, so it is served rather than sorted client-side; the rank-shift
   * read-out against `lens_rank` is then a comparison of two served numbers. */
  composite_rank: number | null;
  /** The same sibling ordering under `lens_value`. Null without a lens. Read
   * against `composite_rank` to see which candidates the alternative formula
   * moves. */
  lens_rank: number | null;
  /** Scorer-faithful accuracy over the request's `samples=` subset. Null without a
   * `samples=` mask, or when this candidate never ran any selected sample. */
  sample_set_accuracy: number | null;
  /** How many of the `samples=` subset this candidate carries a SCOREABLE verdict
   * for — the denominator `sample_set_accuracy` is the mean over. Below the
   * subset size, the candidate sat a different exam from one that answered
   * all of it. */
  sample_set_n: number | null;
  /** Set when the request's lens would have FORKED the record at this node. Only
   * ever set on a closed round's node. */
  divergence: LineageDivergence | null;
  /** This node is inside the counterfactual subtree below a divergence — the client
   * dims it. */
  divergent: boolean;
  /** The cycle_id of the branch that took this candidate's place. Set on the LEFT-
   * BEHIND side of a `supersede` cut (`ForkDirection`) — the tail its own
   * course kept as the record of what ran, while the line continued
   * elsewhere. Null on every candidate still on a line, including both sides
   * of an `offshoot` or `equivalent` cut. Served because a fork is NOT a
   * node: without a name the operator sees a retired attempt and a live one
   * as peers of one round, which is the whole reason a cut records its
   * direction. */
  superseded_by: string | null;
  /** Courses, and the candidates a fork contributed here — on those it is the ⑂
   * stamp marking an attempt the operator cut. */
  course_kind: 'root' | 'fork' | 'diag' | 'sweep' | 'inner' | null;
  /** Courses only — the ONE server-owned run-state (`derive_run_phase`), the same
   * value `/cycles` serves. Null on a candidate, which has no run of its own. */
  run_phase: 'checkin' | 'running' | 'paused' | 'gate' | 'detached' | 'terminal' | null;
  dataset_name: string;
  /** Fork trigger; empty for roots and inner runs. */
  trigger: string;
  /** Which side of this cut the run CONTINUES on, derived from `trigger`
   * (`FORK_DIRECTION`). `offshoot` = this branch hangs off a line that keeps
   * running; `supersede` = this branch IS the line and the PARENT is what was
   * left behind. Null for roots and inner runs, which were not cut from
   * anything. Served, never derived in the client — the two read identically
   * on disk and only this says them apart. */
  fork_direction: 'offshoot' | 'supersede' | 'equivalent' | null;
  /** Operator who cut this fork. */
  steered_by: string | null;
  /** An inner run's benchmark task. Load-bearing: every task runs for every
   * candidate, so the candidate edge alone does not identify an inner run. */
  task: string | null;
  best_accuracy: number | null;
  /** This course's round-0 score. A course that has only run its origin has this
   * and no `best_accuracy`, so reading only `best` blanks its bar. */
  origin_accuracy: number | null;
  hearts: number | null;
  lives_cap: number | null;
}

/** One event on the ray: a projection envelope plus its address. */
export interface RayItem {
  /** The cycle this record belongs to, root → leaf — THE address. */
  path: CycleHop[];
  /** Physical 0-based line index in this cycle's own ledger — the same space as
   * ProjectionEnvelope.sequence, so a live SSE frame de-duplicates against a
   * ray item on (path, offset). SPARSE: server curation drops kinds, so
   * consecutive items may skip offsets; a gap between ray offsets is not a
   * missing record. */
  offset: number;
  /** Effective timestamp: the record's own, raised to its file predecessor's when
   * the two invert (records are stamped at construction but appended later). */
  ts: string;
  /** The ledger record_type — ProjectionEnvelope.kind. */
  kind: 'candidate_minted' | 'decision' | 'command' | 'command_ack' | 'cycle_seed' | 'election' | 'error' | 'llm_call_progress' | 'llm_call' | 'llm_call_start' | 'phase' | 'round_warning' | 'ruler' | 'snapshot' | 'spend_tombstone' | 'token_usage' | 'stream_snapshot';
  /** The record's model_dump — ProjectionEnvelope.payload. */
  payload: Record<string, unknown>;
}

/** One ordered window of a family's chronology, oldest-first. */
export interface RayResponse {
  /** The window, oldest-first. Includes llm_call_progress heartbeats — the client
   * proves liveness across a silent stretch with them before dropping them
   * from the rendered steps. */
  items: RayItem[];
  /** Opaque cursor for the window immediately older than this one; null when this
   * window already reaches the family's beginning. */
  cursor_prev: string | null;
}

/** One outbound SSE frame. Frozen wire shape — a receiver MUST treat an unknown field as a DRIFT SIGNAL, not as */
export interface ProjectionEnvelope {
  /** Closed-set discriminator; every CycleRecord record_type, plus stream_snapshot. */
  kind: 'candidate_minted' | 'decision' | 'command' | 'command_ack' | 'cycle_seed' | 'election' | 'error' | 'llm_call_progress' | 'llm_call' | 'llm_call_start' | 'phase' | 'round_warning' | 'ruler' | 'snapshot' | 'spend_tombstone' | 'token_usage' | 'stream_snapshot';
  /** Envelope shape version. Bump only on a breaking restructure of this class;
   * payload churn is per-kind. */
  version: number;
  /** Target cycle the frame describes; redundant with the channel address but
   * stamped per-frame for fan-in demux. */
  cycle_id: string;
  /** Ledger offset at append. Live-tail frames carry the record's offset; the
   * leading stream_snapshot frame carries the offset captured at subscribe
   * time. */
  sequence: number;
  /** Per-kind body. For record-derived kinds, the record's model_dump; for
   * stream_snapshot, the dashboard.json content + snapshot_at_offset. */
  payload: Record<string, unknown>;
}

/** One page of diagnostic-run records, newest first. */
export interface DiagnosticRunListResponse {
  n: number;
  runs: DiagnosticRunRecord[];
}

/** One OIDC provider currently bound to the active session. */
export interface ConnectedAccount {
  provider: string;
  email: string | null;
}

/** Current identity envelope. Returned by ``GET /auth/me`` only. */
export interface MeResponse {
  user_id: string;
  tenant_id: string;
  issuer: string | null;
  email: string | null;
  name: string | null;
  provider: string | null;
  connected_accounts: ConnectedAccount[];
  available_providers: string[];
  capabilities: string[];
  access_state: 'active' | 'blocked';
  terms_version: string;
  terms_accepted_version: string | null;
}

/** Live snapshot of the abuse-limit knobs vs. usage. */
export interface QuotaStatus {
  spend_used_total_usd: number;
  spend_budget_usd_total: number | null;
  spend_unpriced_tokens: number;
  tokens_used_total: number;
  token_budget_total: number | null;
  concurrent_running: number;
  max_concurrent_cycles: number;
  campaigns_today: number;
  max_campaigns_per_day: number;
}

/** Per-user preferences surfaced in Account → Preferences. */
export interface UserSettings {
  demo_mode_enabled: boolean;
}

/** One bucket of the Activity pane's three stacked bar charts. */
export interface ActivityBucket {
  ts: number;
  spend_usd: number;
  tokens: number;
  requests: number;
  series_spend: Record<string, number>;
  series_tokens: Record<string, number>;
  series_requests: Record<string, number>;
}

/** Time-bucketed spend / requests / tokens over the requested window. */
export interface ActivityResponse {
  window: '15m' | '30m' | '1h' | '3h' | '1d' | '2d' | '1w' | '1mo' | '1y';
  group_by: 'model' | 'api_key';
  since: number;
  until: number;
  buckets: ActivityBucket[];
  series_labels: string[];
  total_spend_usd: number;
  total_tokens: number;
  total_requests: number;
}

export interface BackendResponse {
  /** Backend identifier */
  id: string;
  /** Human-readable backend name */
  name: string;
  /** Backend type (e.g. 'default') */
  backend_type: string;
  /** Backend API base URL */
  base_url: string;
  /** ISO 8601 creation timestamp */
  created_at: string;
}

export interface BackendHealthResponse {
  /** Backend identifier */
  backend_id: string;
  /** Backend API base URL probed */
  base_url: string;
  /** Reachability: 'live', 'unreachable', or 'error' */
  status: 'live' | 'unreachable' | 'error';
  /** ISO 8601 probe timestamp */
  checked_at: string;
  /** Error detail when not 'live' */
  detail: string | null;
}

export interface MachineHolder {
  /** user_id of the operator whose run owns the slot */
  user: string;
  campaign_id: string;
  cycle_id: string;
  /** ISO start time of the holding run; null if still pending */
  started_at: string | null;
}

export interface MachineStatusResponse {
  /** True iff a *different* user holds a running job (the server runs one campaign
   * at a time). */
  busy: boolean;
  /** Who holds the slot; null when free for this caller. */
  holder: MachineHolder | null;
}

/** One row in the dataset registry — backs the Dashboard ``New campaign`` view. */
export interface DatasetIndexEntry {
  /** Slug used as the path segment under `datasets/`. */
  name: string;
  /** Display title (from `dataset.md`). */
  title: string | null;
  /** ``yours`` = user-owned Origin under ``projects/{tenant}/datasets/{slug}/``.
   * ``install`` = content that ships with the product at ``datasets/{slug}/``
   * (benchmarks, demos, ``promptpotter-self``) — tracked in git, so readable
   * by anyone using the install. A ``yours`` slug shadows an ``install`` one. */
  tier: 'yours' | 'install';
  /** Sample bank size from ``cache.json``; ``null`` when the cache has not been
   * materialized, which is not the same as a dataset holding zero usable
   * rows. */
  n_samples: number | null;
}

export interface DatasetIndexResponse {
  datasets: DatasetIndexEntry[];
}

export interface OriginEntry {
  /** Origin content identity — a campaign's root_content_hash (or the dataset's
   * prospective origin hash for a prepared origin) */
  origin_id: string;
  /** Dataset this origin starts from */
  dataset_name: string;
  /** Operator-supplied label, if any */
  label: string;
  /** Dataset sample count; ``null`` if unmaterialized */
  n_samples: number | null;
  /** Active campaigns minted from this origin (0 = prepared, not yet run) */
  n_campaigns: number;
  /** The origin's C0 score, from the canonical campaign's index.json */
  origin_accuracy: number | null;
  /** True = a ready dataset config with no campaign yet */
  prepared: boolean;
  /** ISO 8601 — earliest campaign on this origin */
  created_at: string;
}

export interface OriginListResponse {
  /** Runnable origins, newest first */
  origins: OriginEntry[];
  /** Number of origins */
  total: number;
}

export interface CampaignStorageResponse {
  /** The campaign measured */
  campaign_id: string;
  /** Whole campaign-dir footprint — sum of the six leaves */
  on_disk_bytes: number;
  /** langfuse ground-truth mirror (the input-data copy) */
  dataset_bytes: number;
  /** Backend-produced: node-I/O cache + per-sample arrays */
  connector_bytes: number;
  /** Loop resume point: round searchpoint state + overrides */
  state_bytes: number;
  /** Loop telemetry: streams, prompts, langfuse loop trace */
  trace_bytes: number;
  /** Loop event spine: ledger.jsonl */
  history_bytes: number;
  /** Readable output: manifest + reports + hard_samples */
  reports_bytes: number;
}

export interface WorkspaceStorageEntry {
  campaign_id: string;
  dataset_name: string;
  lifecycle_status: string;
  /** Whole campaign-dir footprint */
  on_disk_bytes: number;
  dataset_bytes: number;
  connector_bytes: number;
  state_bytes: number;
  trace_bytes: number;
  history_bytes: number;
  reports_bytes: number;
}

export interface WorkspaceStorageResponse {
  /** The tenant's real on-disk total — campaigns + caches + other */
  total_bytes: number;
  /** Cross-campaign reuse caches (measurements/ + optimizer_reuse/) — survive
   * delete */
  shared_cache_bytes: number;
  /** Everything else under the tenant: sessions, workspace ledger, dataset/backend
   * stores */
  other_bytes: number;
  /** Fattest-first per-campaign totals (active + archived) */
  campaigns: WorkspaceStorageEntry[];
}

export interface DatasetStorageEntry {
  dataset_name: string;
  /** On disk — the sum of the six leaves */
  total_bytes: number;
  dataset_bytes: number;
  connector_bytes: number;
  state_bytes: number;
  trace_bytes: number;
  history_bytes: number;
  reports_bytes: number;
}

export interface DatasetStorageResponse {
  /** Grand total across the caller's datasets */
  total_bytes: number;
  /** Fattest-first per-dataset leaf splits */
  datasets: DatasetStorageEntry[];
}

export interface CampaignDetailResponse {
  /** Campaign id ({dataset}__{rand6}) — one RUN of an origin */
  campaign_id: string;
  /** Dataset this campaign optimizes */
  dataset_name: string;
  /** Operator-supplied campaign label */
  label: string;
  /** ISO 8601 creation timestamp */
  created_at: string;
  /** The campaign's root cycle id — `cycle_<root_content_hash>`, so it IS the
   * campaign's ORIGIN identity. Campaigns on one declaration share it and
   * differ only in the random `campaign_id` suffix, which is what makes them
   * separate RUNS of that origin; the sidebar groups the forest by this key. */
  root_cycle_id: string;
  /** Backend this campaign optimizes against */
  backend_id: string;
  /** Connector KIND of the campaign's dataset ('termnorm' / 'promptpotter' / …),
   * read off `{dataset}/pipeline.yaml::backend_type`. The webapp's ONE test
   * for a self-optimizing (L4) campaign — it renders the 'inner loops'
   * disclosure and the pp-self panel variants on it. Empty when the dataset
   * config is gone (a campaign outlives its dataset dir); callers treat empty
   * as 'not self-optimizing'. */
  backend_type: string;
  /** UserId of the operator who minted the campaign */
  owner_user_id: string;
  /** Operator visibility intent: 'active' (default sidebar), 'archived' (hidden),
   * 'deleted' (soft-marked, data retained) */
  lifecycle_status: string;
  /** ISO 8601 timestamp of last lifecycle transition */
  lifecycle_changed_at: string;
  /** Optional operator-supplied reason for the last lifecycle transition */
  lifecycle_reason: string;
  /** Content hash of the origin search point — the campaign identity */
  root_content_hash: string;
  /** Frozen CampaignConfig snapshot for this campaign */
  config: Record<string, unknown>;
}

export interface MechanismToggle {
  /** Field key under its group (e.g. 'epsilon_elimination') */
  key: string;
  /** Human-readable toggle name */
  label: string;
  /** What the mechanism does, on vs off */
  description: string;
  /** Default value (preserves stock loop behavior) */
  default: boolean;
}

export interface MechanismGroup {
  /** Group key under optimization.mechanisms (e.g. 'elimination') */
  key: string;
  /** Human-readable group name */
  label: string;
  /** What this group of mechanisms governs */
  description: string;
  /** Toggles in this group, in declared order */
  toggles: MechanismToggle[];
}

/** Self-describing descriptor for the campaign-config mechanism toggles. */
export interface MechanismSchemaResponse {
  /** Mechanism groups, in declared order */
  groups: MechanismGroup[];
}

export interface ConfigKnob {
  /** Dotted CampaignConfig path (or const.<NAME> for a hardcoded floor) */
  path: string;
  /** Short display name (prefix-stripped) */
  label: string;
  /** Effective value in this campaign's frozen config */
  value: unknown;
  /** Where the value came from: default | campaign (operator-set) | required |
   * constant */
  source: string;
}

export interface ConfigEstimandGroup {
  /** Estimand key (selection, difficulty, ability, …) */
  key: string;
  /** Human-readable estimand name */
  label: string;
  /** Plain-language one-liner of what this estimand is */
  doc: string;
  /** Knobs that move this estimand, in declared order */
  knobs: ConfigKnob[];
}

export interface ConfigCoupling {
  /** Coupling id */
  name: string;
  /** Dotted knob paths the coupling relates */
  knobs: string[];
  /** Short display names for those knobs */
  labels: string[];
  /** The shared estimand the knobs co-determine */
  estimand: string;
  /** The relationship rule, plain language */
  relation: string;
  /** What goes wrong when the combination is violated */
  consequence: string;
  /** collision (soundness) | inert (wasted knob) | info (relationship) */
  severity: string;
  /** True when this campaign's config is in the violating combination */
  active: boolean;
}

/** The config-map for one campaign: every knob grouped by the statistical */
export interface ConfigMapResponse {
  /** Estimand groups, in declared order */
  groups: ConfigEstimandGroup[];
  /** Declared couplings, active ones flagged */
  couplings: ConfigCoupling[];
}

/** Every field optional — absent inherits the parent — applied to the fork's snapshot at */
export interface ConfigOverrides {
  max_rounds: number | null;
  spend_budget_usd: number | null;
  token_budget: number | null;
  l1_patience: number | null;
  l2_patience: number | null;
  l3_patience: number | null;
  pobb_epsilon: number | null;
  per_round_resubset: boolean | null;
  schema_field_rename: boolean | null;
  scoring: string | Record<string, string> | null;
}

/** The dataset's ``pipeline.yaml`` declares the MAXIMUM tunable surface; a campaign may only */
export interface NodeSearchNarrowing {
  param_keys: string[] | null;
  param_allowed_values: Record<string, string[]>;
}

/** ``pipeline_overlay`` merges ON TOP of the dataset overlay for this cycle only. */
export interface CycleSeed {
  origin_prompt_fields: Record<string, unknown>;
  pipeline_overlay: Record<string, unknown>;
  /** Per-fork search-space lock edits (param-key subset + allowed-values) —
   * overrides the campaign's mint-time narrowing for this cycle only, the
   * cycle-level peer of the campaign-wide
   * `CampaignConfig.optimizer_narrowing`. Empty for an unedited fork or a
   * campaign-from-origin seed. */
  optimizer_narrowing: Record<string, NodeSearchNarrowing>;
  config_overrides: ConfigOverrides;
  /** C0 lineage provenance — 'fork_seed' | 'campaign_origin'; empty when the seed
   * carries no origin (an L2/L3 rebase replays its own). */
  origin_source: string;
}

export interface OriginGateDecisionPayload {
  campaign_id: string;
  cycle_id: string;
  decision: 'rescore' | 'proceed' | 'abort';
}

// The coarse run-state axis (domain/phases.py::RunPhase).
export type RunPhase = 'checkin' | 'running' | 'paused' | 'gate' | 'detached' | 'terminal';

// The fine-grained activity axis, `dashboard.json::state` (domain/phases.py::DashboardState).
export type DashboardState = 'init' | 'origin' | 'scoring' | 'between_samples' | 'between_candidates' | 'l1_generate' | 'l2_refining' | 'l3_replanning' | 'escalation' | 'stopped';

// Every kind `POST /commands/{kind}` dispatches (command_dispatcher.py).
export type CommandKind = 'archive-campaign' | 'change-spend-budget' | 'cleanup-empty-cycles' | 'delete-campaign' | 'delete-cycle' | 'edit-draft-campaign' | 'fork-cycle' | 'mint-campaign' | 'origin-gate-decision' | 'pause-cycle' | 'register-backend' | 'replace-dataset' | 'resolve-origin' | 'set-allowed-models' | 'set-campaign-label' | 'set-sample-lookahead' | 'skip-searchpoint' | 'start-checkin' | 'start-run' | 'step-cycle' | 'unarchive-campaign';

// Kinds no activity item is ever made of — the ray drops them and the translator
// returns null. Complement of domain/projection_envelope.py::RENDERS_AS_ACTIVITY.
export type NonActivityKind = 'decision' | 'election' | 'ruler' | 'spend_tombstone' | 'token_usage';

// Operator-facing label per terminal reason (StopReason). Mirror of
// domain/phases.py::STOP_REASON_INFO — the single label source.
export const STOP_REASON_LABELS: Record<string, string> = {
  'perfect_score': 'Perfect score',
  'target_hit': 'Target reached',
  'max_rounds': 'Max rounds',
  'lives_exhausted': 'Out of lives',
  'hard_cap_reached': 'Round cap',
  'sweep_complete': 'Sweep complete',
  'diag_complete': 'Diagnostic complete',
  'l3_patience_exhausted': 'Converged (L3 patience)',
  'rebased_to_fork': 'Rebased to fork',
  'paused': 'Paused',
  'escalation_abort': 'Escalation abort',
  'spend_budget': 'Spend budget reached',
  'token_budget': 'Token budget reached',
  'origin_gate': 'Origin gate (unhealthy origin)',
  'backend_unreachable': 'Backend unreachable',
  'crashed': 'Crashed',
  'producer_vanished': 'Producer vanished',
  'render_error': 'Render error',
  'diverged': 'Diverged',
  'optimizer_timeout': 'Optimizer timeout',
};

// Abort-lens variant -> operator label, in picklist order. Mirror of
// domain/results.py::ABORT_LENS_LABELS, whose keys are asserted against the API edge's
// own `_ABORT_SUPPRESS` at import. Don't hand-list these.
export const ABORT_LENS_LABELS: Record<string, string> = {
  'epsilon_off': 'No ε-elimination',
  'lock_in_off': 'No lock-in',
  'collapsed_off': 'No collapse cut',
  'all_off': 'No early abort',
};

export interface EvaluatorMeta {
  name: string;
  scope: "per_round" | "per_sample";
  direction: "high" | "low";
  node_type: string | null;
  from_rows: boolean;
  description: string;
}

// The evaluator registry, mirrored from application/scoring/evaluators.py.
export const EVALUATOR_META: EvaluatorMeta[] = [
  { name: 'accuracy', scope: 'per_round', direction: 'high', node_type: null, from_rows: true, description: 'Mean per-sample score across non-deprecated samples.' },
  { name: 'error_rate', scope: 'per_round', direction: 'low', node_type: null, from_rows: true, description: 'Fraction of queries that errored (ERROR predicted or exception).' },
  { name: 'degraded_rate', scope: 'per_round', direction: 'low', node_type: null, from_rows: true, description: 'Fraction of queries that completed with pipeline degradation warnings.' },
  { name: 'source_recall', scope: 'per_round', direction: 'high', node_type: 'candidate_source', from_rows: false, description: "Fraction of queries where GT appears in a candidate_source node's output." },
  { name: 'candidate_recall', scope: 'per_round', direction: 'high', node_type: 'ranker', from_rows: false, description: "Fraction of queries where GT appears in a ranker node's final_ranking." },
  { name: 'cache_hit_rate', scope: 'per_round', direction: 'high', node_type: 'cache', from_rows: false, description: 'Fraction of queries resolved by a cache node (non-null timing).' },
  { name: 'retrieval_shortfall', scope: 'per_sample', direction: 'high', node_type: null, from_rows: false, description: 'Per-sample min(observed/target, 1.0) across nodes with max_*/num_* limits on list-valued outputs. 1.0 = target met or exceeded.' },
  { name: 'mean_retrieval_shortfall', scope: 'per_round', direction: 'high', node_type: null, from_rows: false, description: "Mean of retrieval_shortfall across the round's results." },
];
