// AUTOGENERATED by scripts/build_ts_types.py — do not hand-edit.
// Run `python scripts/build_ts_types.py` to regenerate from the Pydantic
// models in `promptpotter/` and commit the diff alongside any schema change.

/** Display-summary row for `dashboard.json::rounds[].candidates` — chart/lineage/sparkline subset of `ScoredCandidate`. */
export interface RoundSummaryCandidate {
  candidate_id: string;
  label: string;
  accuracy: number;
  composite_fitness: number;
  scored_samples: number;
  expected_samples: number;
  is_winner: boolean;
  evaluators: Record<string, number>;
  changes_description: string;
  partial_reason: string;
  theta: number | null;
  theta_se: number | null;
  composite_ci_lo: number | null;
  composite_ci_hi: number | null;
}

/** Context-aware degradation verdict for a round (origin included), computed */
export interface DegradationHealth {
  grade: 'healthy' | 'degraded' | 'critical';
  reasons: string[];
  samples: number;
  structural_count: number;
  transient_count: number;
  no_result_count: number;
  degraded_rate: number;
  consecutive_degraded_rounds: number;
  prior_clean_rounds: number;
  dominant_node: string | null;
  node_failure_rates: Record<string, number>;
  node_warnings: Record<string, string[]>;
  ci_lo: number;
  ci_hi: number;
  suggested_action: string | null;
}

/** One cell's paired (variant − origin) composite difference. */
export interface OuterCellEffect {
  cell: string;
  variant_fitness: number;
  origin_fitness: number;
  diff: number;
}

/** The pooled blocked-paired verdict for a round's target variant. */
export interface OuterVerdict {
  variant_id: string;
  variant_label: string;
  per_cell: OuterCellEffect[];
  effect: number;
  se: number;
  ci_lo: number;
  ci_hi: number;
  n_cells: number;
  decision: string;
  mde_remaining: number;
}

/** Display row for `dashboard.json::rounds[]` — webapp's completed-round source. */
export interface RoundSummary {
  round: number;
  accuracy: number;
  composite_fitness: number;
  cumulative_accuracy: number;
  cumulative_theta: number | null;
  candidates: RoundSummaryCandidate[];
  selection: number[];
  health: DegradationHealth | null;
  outer_verdict: OuterVerdict | null;
}

/** One on-demand workspace-scope diagnostic run — the ``verify`` and ``noise-floor`` */
export interface DiagnosticRunRecord {
  ts: string;
  dataset: string;
  source_campaign: string;
  source_cycle: string;
  source_label: string;
  source_candidate_id: string;
  config_hash: string;
  samples_requested: number;
  samples_added: number;
  workspace_n: number;
  workspace_accuracy: number;
  workspace_composite: number;
  source_campaign_accuracy: number;
  source_campaign_composite: number;
  source_campaign_n: number;
  noise_floor_k: number | null;
  noise_floor_mean: number | null;
  noise_floor_ci_lo: number | null;
  noise_floor_ci_hi: number | null;
  noise_floor_raw: number[] | null;
}

/** One spend sub-bucket (backend or optimizer-loop). Mutated only by */
export interface SpendBucket {
  used_usd: number;
  input_tokens: number;
  output_tokens: number;
  rate_known: boolean;
  model: string | null;
  unpriced_tokens: number;
}

/** ``state.spend`` — two-bucket spend rollup + total. */
export interface SpendRollup {
  backend: SpendBucket;
  loop: SpendBucket;
  total_used_usd: number;
}

export interface DatasetItem {
  sample_id: number;
  query: string;
  ground_truth: string;
  task: string | null;
  /** Times this sample has been tried */
  n_obs: number;
  /** Queue-mechanism's blended objective on this sample for a brand-new candidate
   * (prior N(0, sigma_theta**2)) vs the best fitted candidate. The live
   * adaptive queue mechanism re-evaluates per step. None when unmeasured. */
  pick_score: number | null;
  /** Rasch difficulty delta_s (higher = harder). None when unmeasured. */
  delta: number | null;
  /** SE of delta_s (large = barely measured). None when unmeasured. */
  delta_se: number | null;
  /** Marginal hit prob the seed-centred decision-IG reads — see
   * ``adaptive_queue_mechanism.marginal_hit_probability``. Near 0.5 =
   * contested at seed; near 0/1 = predictable. None when unmeasured. */
  p_hat: number | null;
}

export interface DatasetPreviewResponse {
  name: string;
  row_count: number;
  /** Declared training-bank fold size from `campaign.json::dataset_split`. */
  split_train: number | null;
  /** Declared held-out test fold size (not materialized). */
  split_test: number | null;
  items: DatasetItem[];
}

export interface MeasurementDot {
  /** Opaque ordinal for lex sort + uniqueness (encodes ts/run/idx or round/cand). */
  ord: string;
  hit: boolean;
  /** Short human label, e.g. 'R3 cand 2'. */
  label: string;
}

export interface SampleSeries {
  sample_id: number;
  measurements: MeasurementDot[];
}

export interface MeasurementSeriesResponse {
  name: string;
  scope: 'cycle' | 'campaign' | 'dataset';
  items: SampleSeries[];
}

/** One operator-editable config param of a node — the FULL config surface the */
export interface NodeConfigParam {
  key: string;
  value: unknown;
  kind: string;
  options: string[];
  description: string;
  optimizer_locked: boolean;
  optimizer_tunable: boolean;
}

/** Resolved output schema for a pipeline node. */
export interface NodeOutputSchema {
  fields: string[];
  field_descriptions: Record<string, string>;
  json_schema: Record<string, unknown>;
}

/** Target pipeline view for a dataset overlay. `view` drives the webapp chat-pane hero; */
export interface DatasetPipelineResponse {
  name: string;
  connector: string;
  backend_type: string | null;
  pipeline: Record<string, unknown>;
  view: Record<string, unknown> | null;
  node_config_schema: Record<string, NodeConfigParam[]>;
  node_output_schema: Record<string, NodeOutputSchema | null>;
  origin_prompt_fields: Record<string, unknown> | null;
}

export interface ActiveSessionResponse {
  /** Tenant the active session belongs to */
  tenant_id: string;
  /** Active session id */
  session_id: string;
  /** Active campaign id (pinned by the webapp) */
  campaign_id: string;
  /** Active cycle id within the campaign */
  cycle_id: string;
}

export interface CycleListEntry {
  /** Campaign the cycle belongs to */
  campaign_id: string;
  cycle_id: string;
  parent_session_id: string;
  /** Immediate parent for siblings (forks/sweeps/diag); null for roots. Sidebar
   * uses this to nest siblings. */
  parent_cycle_id: string | null;
  dataset_name: string;
  backend_id: string;
  sibling_kind: 'root' | 'fork' | 'diag' | 'sweep';
  unit_kind: 'session' | 'divergent_resume' | 'user_fork' | 'auto_rebase';
  is_root: boolean;
  status: string;
  /** The single run-state value (RunPhase) — checkin (origin still being authored,
   * pre-loop) / running / paused / detached / terminal. Computed once by
   * derive_run_phase from lifecycle + control flags + freshness; every picker
   * dot and badge reads this, none re-derive it. 'checkin' wins first (the
   * campaign hasn't run); 'terminal' pairs with `status` for the reason
   * label. */
  run_phase: 'checkin' | 'running' | 'paused' | 'detached' | 'terminal';
  best_accuracy: number | null;
  n_rounds: number;
  created_at: string;
  updated_at: string;
  /** True once an operator manually intervened (e.g. skip-searchpoint); the cycle
   * is babysat and no longer purely reproducible. Drives the 'babysat' badge;
   * orthogonal to run_phase. */
  human_intervened: boolean;
}

export interface CyclesResponse {
  tenant_id: string;
  /** Active campaign per active_session.json; null when no session is active. */
  active_campaign_id: string | null;
  /** Active cycle per active_session.json; null when no session is active. */
  active_cycle_id: string | null;
  cycles: CycleListEntry[];
}

/** The 202 response shape declared in ``m12-api-openapi.yaml``. */
export interface CommandAcceptedBody {
  /** Stable id of the appended `CommandRecord`. */
  command_id: string;
  /** Echo of the request's `Idempotency-Key`. */
  correlation_id: string;
  /** Offset at which the `CommandRecord` was appended. */
  ledger_sequence: number;
}

export interface CampaignSummary {
  /** Stable campaign id ({dataset}__{origin hash}) */
  campaign_id: string;
  /** Dataset this campaign optimizes */
  dataset_name: string;
  /** Operator-supplied campaign label */
  label: string;
  /** Status of the campaign's most-recent session */
  status: string;
  /** ISO 8601 creation timestamp */
  created_at: string;
  /** The campaign's first session's root cycle id */
  root_cycle_id: string;
  /** Backend this campaign optimizes against */
  backend_id: string;
  /** Number of sessions (re-runs of the declaration) in the campaign */
  session_count: number;
  /** UserId of the operator who minted the campaign */
  owner_user_id: string;
  /** Operator visibility intent: 'active' (default sidebar), 'archived' (hidden),
   * 'deleted' (soft-marked, data retained) */
  lifecycle_status: string;
  /** ISO 8601 timestamp of last lifecycle transition */
  lifecycle_changed_at: string;
  /** Optional operator-supplied reason for the last lifecycle transition */
  lifecycle_reason: string;
}

export interface CampaignListResponse {
  /** List of campaign summaries */
  campaigns: CampaignSummary[];
  /** Total number of campaigns */
  total: number;
}

/** One session in a campaign's forest — a root cycle + its forks. */
export interface SessionSummary {
  /** The session's root cycle id */
  root_cycle_id: string;
  /** 1-based session ordinal within the campaign */
  session_index: number;
  /** Session root cycle status */
  status: string;
  /** Rounds completed on the session root cycle */
  n_rounds: number;
  /** Best round accuracy */
  best_accuracy: number | null;
  /** ISO 8601 session creation timestamp */
  created_at: string;
  /** ISO 8601 last write */
  updated_at: string;
}

export interface FileEntry {
  /** Path relative to the scope root, forward slashes */
  path: string;
  /** Which root the path is under */
  scope: 'cycle' | 'campaign';
  /** File size in bytes */
  size: number;
  /** ISO 8601 UTC modification time */
  mtime: string;
}

export interface FilesResponse {
  campaign_id: string;
  cycle_id: string;
  entries: FileEntry[];
}

export interface FileContentResponse {
  campaign_id: string;
  cycle_id: string;
  scope: 'cycle' | 'campaign';
  path: string;
  size: number;
  mtime: string;
  content_type: 'json' | 'markdown' | 'log' | 'text' | 'binary';
  /** UTF-8 text content; None when binary or oversized */
  content: string | null;
}

export interface CampaignLineageCandidate {
  /** Stable id assigned at L1-score time */
  candidate_id: string;
  /** Short L1-generated description */
  label: string;
  /** Per-candidate accuracy */
  accuracy: number | null;
  /** The candidate's fitness under the run's active formula (equals accuracy when
   * no formula was active) — served verbatim from the dashboard round summary
   * so the lineage tree can honor the composite headline selection on
   * settled/sibling cycles too, never recomputed client-side. */
  composite_fitness: number | null;
  /** Final rank within the round */
  rank: number | null;
  /** True for the round's elected winner */
  is_winner: boolean;
  /** Difficulty-adjusted Rasch ability the winner was elected on
   * (`elect_round_winner`) — the subset-invariant metric that explains a
   * lower-accuracy winner. Null for candidates outside the round's election
   * fit. */
  theta: number | null;
  /** Laplace SE on `theta` (for a CI on the ability). */
  theta_se: number | null;
  /** This candidate's fitness under the request's `score:` lens formula, recomputed
   * from its stored evaluator namespace via the single scoring operation (the
   * same one the mask divergence rides). Null without a `score:` lens, or
   * when the candidate's namespace can't satisfy the formula. */
  lens_value: number | null;
  /** Scorer-faithful accuracy over the request's `samples=` subset, re-scored
   * server-side from this candidate's per-sample rows (the same
   * `materialize_row_derivable` the mask divergence rides). Null without a
   * `samples=` mask, or when the candidate never ran any selected sample. */
  sample_set_accuracy: number | null;
  /** How many of the `samples=` subset this candidate actually ran (the honest 'n
   * of N' — older candidates that skipped some chosen samples read a smaller
   * n). Null without a `samples=` mask. */
  sample_set_n: number | null;
}

export interface CampaignLineageRound {
  /** Round number within the cycle (1-indexed) */
  round: number;
  /** Round label — winner's L1 description */
  label: string;
  /** Round-level accuracy (winner) */
  accuracy: number | null;
  /** The adopted lineage rescored over EVERY sample probed so far — the cross-
   * round-comparable frontier (matches the trend chart). The webapp paints
   * the WINNER node with this so the lineage spine reads as honest progress,
   * not the per-round subset swing; sibling alternatives keep their own
   * subset `accuracy`. */
  cumulative_accuracy: number | null;
  /** All candidates scored this round, sorted by rank */
  candidates: CampaignLineageCandidate[];
}

export interface CampaignLineageCycle {
  cycle_id: string;
  sibling_kind: 'root' | 'fork' | 'diag' | 'sweep';
  immediate_parent_cycle_id: string | null;
  fork_from_round: number | null;
  fork_from_candidate_id: string | null;
  trigger: string;
  steered_by: string | null;
  round_column_offset: number;
  status: string;
  dataset_name: string;
  best_accuracy: number | null;
  rounds: CampaignLineageRound[];
}

/** A mask divergence point — the first node on a branch an alternative scoring */
export interface LineageDivergence {
  /** Lineage node id, formatted `{cycle_id}::r{round}` */
  node_key: string;
  cycle_id: string;
  round: number;
  /** The candidate the masked criterion would have elected instead (measured, so
   * nameable); null when the round would simply have held on origin. */
  alternative_candidate_id: string | null;
}

export interface CampaignLineageResponse {
  campaign_id: string;
  /** Every cycle in the campaign (root + forks + sweeps + diag). Sorted by cycle
   * id; lay out via immediate_parent_cycle_id. */
  cycles: CampaignLineageCycle[];
  divergences: LineageDivergence[];
  /** Node keys of the counterfactual subtree to render dimmed. */
  divergent: string[];
}

/** One page of diagnostic-run records, newest first. */
export interface DiagnosticRunListResponse {
  n: number;
  runs: DiagnosticRunRecord[];
}

// Operator-facing label per terminal reason (StopReason). Mirror of
// domain/phases.py::STOP_REASON_INFO — the single label source.
export const STOP_REASON_LABELS: Record<string, string> = {
  'perfect_score': 'Perfect score',
  'target_hit': 'Target reached',
  'max_rounds': 'Max rounds',
  'hard_cap_reached': 'Round cap',
  'sweep_complete': 'Sweep complete',
  'diag_complete': 'Diagnostic complete',
  'l3_patience_exhausted': 'Converged (L3 patience)',
  'rebased_to_fork': 'Rebased to fork',
  'paused': 'Paused',
  'escalation_abort': 'Escalation abort',
  'spend_budget': 'Spend budget reached',
  'token_budget': 'Token budget reached',
  'origin_gate': 'Origin gate (unhealthy origin)',
  'backend_unreachable': 'Backend unreachable',
  'crashed': 'Crashed',
  'producer_vanished': 'Producer vanished',
  'render_error': 'Render error',
  'diverged': 'Diverged',
  'optimizer_timeout': 'Optimizer timeout',
};
