// The wire types, re-exported from `types.generated.ts`: change the Pydantic model and regenerate.

export type {
  AbilityReading,
  ArmOutcome,
  ArchiveReport,
  ActiveSessionResponse,
  CampaignListResponse,
  CampaignRunsWith,
  CampaignSummary,
  RunsWithParam,
  VendorModels,
  RankedEdit,
  EffectProvenance,
  ConfigKeys,
  EditSpread,
  SubjectReading,
  WinnerChainPoint,
  Comparability,
  ArmReplicate,
  FactorCell,
  FactorGridReading,
  FactorLevel,
  FactorReading,
  EvidenceVariance,
  EvidencePower,
  OrderConfound,
  MetricSpec,
  PairwiseComparison,
  MetricReading,
  HeadToHead,
  HeadlineLift,
  HeadToHeadRow,
  Evidence,
  CommandAcceptedBody,
  NodeSearchNarrowing,
  CycleHop,
  BandedValue,
  BenchPassProgress,
  BenchReading,
  BenchScore,
  CycleListEntry,
  CyclesResponse,
  DatasetItem,
  DatasetPipelineResponse,
  NestedPipelineRef,
  Cell,
  CellCandidate,
  CellRow,
  CellsResponse,
  CellSpan,
  DegradationHealth,
  FileContentResponse,
  FileEntry,
  FilesResponse,
  BackendWarning,
  CatchUpLogEntry,
  BackpressureReading,
  DashboardError,
  LineageDivergence,
  LineageNode,
  LiveDashboardState,
  LoopWarning,
  RunLimits,
  CurrentRound,
  DashboardCandidate,
  LiveCandidate,
  ModelCapability,
  NodeConfigParam,
  NodeOutputSchema,
  NodeReach,
  OptimizerFact,
  OptimizerLimit,
  OptimizerPipelineResponse,
  PipelineView,
  PipelineViewEdge,
  PipelineViewNode,
  OverlapMember,
  OverlapReading,
  PanelPrecision,
  RayItem,
  RayResponse,
  ProjectionEnvelope,
  NonActivityKind,
  DashboardSample,
  RoundResult,
  RoundSummary,
  RoundSummaryCandidate,
  ScoreboardRow,
  ScoredCandidate,
  ValidationFailure,
  VerifyPassProgress,
  VerifyReading,
  SpendBucket,
  SpendRollup,
  KindSpend,
  MeteredSpend,
  LifetimeSpend,
  ForkRemainder,
  ActivityBucket,
  ActivityResponse,
  BackendHealthResponse,
  HealthResponse,
  LifecycleFilter,
  BackendResponse,
  CampaignPipelineResponse,
  CampaignStorageResponse,
  ConfigCoupling,
  ConfigEstimandGroup,
  ConfigKnob,
  ConfigMapResponse,
  ConnectedAccount,
  DatasetIndexEntry,
  DatasetIndexResponse,
  DatasetStorageEntry,
  DatasetStorageResponse,
  ForkPreviewResponse,
  MachineHolder,
  MachineStatusResponse,
  KnobRow,
  ManifestNodeOverlay,
  NodeKnobs,
  OptimizerEntry,
  OptimizerKnobsResponse,
  OptimizerRoster,
  MeResponse,
  OriginEntry,
  OriginListResponse,
  QuotaStatus,
  UserSettings,
  WorkspaceStorageEntry,
  WorkspaceStorageResponse,
} from "./types.generated";

import type { CycleListEntry, LiveDashboardState } from "./types.generated";

// Hand-written: `HeatmapScope` reaches the wire only as a query param. No workspace scope, since
// samples differ per dataset.
export type HardSamplesScope = "cycle" | "campaign" | "dataset";

export type MintKind = CycleListEntry["mint_kind"];

export type MeasuredUnit = LiveDashboardState["measured_unit"];

