// AUTOGENERATED by scripts/build_ts_types.py — do not hand-edit.
// Run `python scripts/build_ts_types.py` to regenerate from the Pydantic
// models in `promptpotter/` and commit the diff alongside any schema change.

/** Origin row for `dashboard.json::origin` — separate from `rounds[]` since origin has no candidates/fitness. */
export interface OriginSummary {
  accuracy: number;
  samples: number;
}

/** Display-summary row for `dashboard.json::rounds[].candidates` — chart/lineage/sparkline subset of `CandidateScore`. */
export interface RoundSummaryCandidate {
  candidate_id: string;
  label: string;
  accuracy: number;
  composite_fitness: number;
  scored_samples: number;
  expected_samples: number;
  is_winner: boolean;
  evaluators: Record<string, number>;
  changes_description: string;
}

/** Display row for `dashboard.json::rounds[]` — webapp's completed-round source. */
export interface RoundSummary {
  round: number;
  accuracy: number;
  composite_fitness: number;
  candidates: RoundSummaryCandidate[];
}

/** One on-demand candidate verification → webapp Verify tab. */
export interface DiagnosticRunRecord {
  ts: string;
  dataset: string;
  source_campaign: string;
  source_cycle: string;
  source_label: string;
  source_candidate_id: string;
  config_hash: string;
  samples_requested: number;
  samples_added: number;
  workspace_n: number;
  workspace_accuracy: number;
  workspace_composite: number;
  source_campaign_accuracy: number;
  source_campaign_composite: number;
  source_campaign_n: number;
}

/** One spend sub-bucket (backend or optimizer-loop). Mutated only via */
export interface SpendBucket {
  used_usd: number;
  input_tokens: number;
  output_tokens: number;
  rate_known: boolean;
  model: string | null;
}

/** ``state.spend`` — two-bucket spend rollup + total. */
export interface SpendRollup {
  backend: SpendBucket;
  loop: SpendBucket;
  total_used_usd: number;
  budget_usd: number | null;
}

/** One entry in ``recent_backend_warnings`` — backend transport retry / 429 / 5xx surface. */
export interface BackendWarning {
  ts: string;
  kind: string;
  attempt: number | null;
  max_attempts: number | null;
  wait_s: number | null;
  error_class: string | null;
  status_code: number | null;
  final: boolean;
  query: string | null;
}

/** One paired-PoBB backfill event appended by ``candidate_block.append_backfill``. */
export interface BackfillLogEntry {
  round: number;
  candidate_idx: number;
  candidate_total: number;
  sample_id: number;
  prior_ids: string[];
}

/** ``state.in_flight`` — the optimizer LLM call currently in progress. */
export interface InFlightCall {
  call_id: string;
  node: string;
  model: string | null;
  round: number | null;
  candidate_idx: number | null;
  started_at_ms: number;
}

/** ``dashboard.json`` — operator-facing snapshot, polled by the webapp. */
export interface LiveDashboardState {
  campaign_id: string;
  cycle_id: string;
  session_id: string;
  state: string;
  state_since: string;
  stop_reason: string | null;
  round: number;
  candidate: string;
  query: string;
  patience: string;
  origin: OriginSummary;
  rounds: RoundSummary[];
  best: number;
  current_acc: number;
  composite_fitness_formula: string | null;
  degraded_count: number;
  error_count: number;
  backend_retry_count: number;
  recent_backend_warnings: BackendWarning[];
  total_queries_scored: number;
  total_backend_calls: number;
  current_query_payload: string | null;
  current_sample_id: number | null;
  hard_sample_order: number[] | null;
  last_query_elapsed_s: number;
  wallclock_serialized_at: string | null;
  n_variants: number;
  sp_budget_ttest: number;
  spend: SpendRollup;
  in_flight: InFlightCall | null;
  backfill_log: BackfillLogEntry[];
  current_round: Record<string, unknown>;
}

export interface DatasetItem {
  sample_id: number;
  query: string;
  ground_truth: string;
  task: string | null;
  /** Times this sample has been tried */
  n_obs: number;
  /** Picker's blended objective on this sample for a brand-new candidate (prior
   * N(0, sigma_theta**2)) vs the best fitted candidate. Live picker re-
   * evaluates per step. None when unmeasured. */
  pick_score: number | null;
  /** Rasch difficulty delta_s (higher = harder). None when unmeasured. */
  delta: number | null;
  /** SE of delta_s (large = barely measured). None when unmeasured. */
  delta_se: number | null;
  /** Marginal hit prob the seed-centred decision-IG reads — see
   * ``adaptive_picker.marginal_hit_probability``. Near 0.5 = contested at
   * seed; near 0/1 = predictable. None when unmeasured. */
  p_hat: number | null;
}

export interface DatasetPreviewResponse {
  name: string;
  row_count: number;
  /** Declared training-bank fold size from `campaign.json::dataset_split`. */
  split_train: number | null;
  /** Declared held-out test fold size (not materialized). */
  split_test: number | null;
  items: DatasetItem[];
}

export interface MeasurementDot {
  /** Opaque ordinal for lex sort + uniqueness (encodes ts/run/idx or round/cand). */
  ord: string;
  hit: boolean;
  /** Short human label, e.g. 'R3 cand 2'. */
  label: string;
}

export interface SampleSeries {
  sample_id: number;
  measurements: MeasurementDot[];
}

export interface MeasurementSeriesResponse {
  name: string;
  scope: 'cycle' | 'campaign' | 'dataset';
  items: SampleSeries[];
}

/** Target pipeline view for a dataset overlay. `view` drives the webapp chat-pane hero; */
export interface DatasetPipelineResponse {
  name: string;
  connector: string;
  pipeline: Record<string, unknown>;
  view: Record<string, unknown> | null;
}

export interface ActiveSessionResponse {
  /** Tenant the active session belongs to */
  tenant_id: string;
  /** Active session id */
  session_id: string;
  /** Active campaign id (pinned by the webapp) */
  campaign_id: string;
  /** Active cycle id within the campaign */
  cycle_id: string;
}

export interface CycleListEntry {
  /** Campaign the cycle belongs to */
  campaign_id: string;
  cycle_id: string;
  parent_session_id: string;
  /** Immediate parent for siblings (forks/sweeps/diag); null for roots. Sidebar
   * uses this to nest siblings. */
  parent_cycle_id: string | null;
  dataset_name: string;
  backend_id: string;
  sibling_kind: 'root' | 'fork' | 'diag' | 'sweep';
  unit_kind: 'session' | 'divergent_resume' | 'user_fork' | 'l3_fork';
  is_root: boolean;
  status: string;
  best_accuracy: number | null;
  n_rounds: number;
  created_at: string;
  updated_at: string;
}

export interface CyclesResponse {
  tenant_id: string;
  /** Active campaign per active_session.json; null when no session is active. */
  active_campaign_id: string | null;
  /** Active cycle per active_session.json; null when no session is active. */
  active_cycle_id: string | null;
  cycles: CycleListEntry[];
}

export interface CreateForkRequest {
  /** Round the operator endorsed (audit-trail only in the MVP) */
  round: number;
  /** Candidate the operator endorsed (audit-trail only in the MVP) */
  candidate_id: string;
}

export interface CreateForkResponse {
  campaign_id: string;
  fork_cycle_id: string;
  /** Launch the fork; active pointer has been retargeted so bare `resume` picks it
   * up. */
  cli_command: string;
  active_pointer_retargeted: boolean;
}

export interface StopCycleResponse {
  campaign_id: string;
  cycle_id: string;
  flag_written: boolean;
}

export interface DeleteCycleResponse {
  campaign_id: string;
  cycle_id: string;
  deleted: boolean;
  /** Populated only when the delete was a no-op. */
  reason: string;
}

export interface CleanupEmptyResponse {
  campaign_id: string;
  root_cycle_id: string;
  /** Removed dirs in deletion order (leaves first). */
  deleted_cycle_ids: string[];
  /** Considered but skipped — ``{cycle_id, reason}`` each. */
  skipped: Record<string, string>[];
}

export interface CampaignSummary {
  /** Stable campaign id ({dataset}__{origin hash}) */
  campaign_id: string;
  /** Dataset this campaign optimizes */
  dataset_name: string;
  /** Operator-supplied campaign label */
  label: string;
  /** Status of the campaign's most-recent session */
  status: string;
  /** ISO 8601 creation timestamp */
  created_at: string;
  /** The campaign's first session's root cycle id */
  root_cycle_id: string;
  /** Backend this campaign optimizes against */
  backend_id: string;
  /** Number of sessions (re-runs of the declaration) in the campaign */
  session_count: number;
}

export interface CampaignListResponse {
  /** List of campaign summaries */
  campaigns: CampaignSummary[];
  /** Total number of campaigns */
  total: number;
}

/** One session in a campaign's forest — a root cycle + its forks. */
export interface SessionSummary {
  /** The session's root cycle id */
  root_cycle_id: string;
  /** 1-based session ordinal within the campaign */
  session_index: number;
  /** Session root cycle status */
  status: string;
  /** Rounds completed on the session root cycle */
  n_rounds: number;
  /** Best round accuracy */
  best_accuracy: number | null;
  /** ISO 8601 session creation timestamp */
  created_at: string;
  /** ISO 8601 last write */
  updated_at: string;
}

export interface FileEntry {
  /** Path relative to the scope root, forward slashes */
  path: string;
  /** Which root the path is under */
  scope: 'cycle' | 'campaign';
  /** File size in bytes */
  size: number;
  /** ISO 8601 UTC modification time */
  mtime: string;
}

export interface FilesResponse {
  campaign_id: string;
  cycle_id: string;
  entries: FileEntry[];
}

export interface FileContentResponse {
  campaign_id: string;
  cycle_id: string;
  scope: 'cycle' | 'campaign';
  path: string;
  size: number;
  mtime: string;
  content_type: 'json' | 'markdown' | 'log' | 'text' | 'binary';
  /** UTF-8 text content; None when binary or oversized */
  content: string | null;
}

export interface CampaignLineageCandidate {
  /** Stable id assigned at L1-score time */
  candidate_id: string;
  /** Short L1-generated description */
  label: string;
  /** Per-candidate accuracy */
  accuracy: number | null;
  /** Final rank within the round */
  rank: number | null;
  /** True for the round's elected winner */
  is_winner: boolean;
}

export interface CampaignLineageRound {
  /** Round number within the cycle (1-indexed) */
  round: number;
  /** Round label — winner's L1 description */
  label: string;
  /** Round-level accuracy (winner) */
  accuracy: number | null;
  /** All candidates scored this round, sorted by rank */
  candidates: CampaignLineageCandidate[];
}

export interface CampaignLineageCycle {
  cycle_id: string;
  sibling_kind: 'root' | 'fork' | 'diag' | 'sweep';
  immediate_parent_cycle_id: string | null;
  fork_from_round: number | null;
  fork_from_candidate_id: string | null;
  trigger: string;
  round_column_offset: number;
  status: string;
  dataset_name: string;
  best_accuracy: number | null;
  rounds: CampaignLineageRound[];
}

export interface CampaignLineageResponse {
  campaign_id: string;
  /** Every cycle in the campaign (root + forks + sweeps + diag). Sorted by cycle
   * id; lay out via immediate_parent_cycle_id. */
  cycles: CampaignLineageCycle[];
}

export interface PerQueryRow {
  query: string;
  sample_id: number;
  n_measurements: number;
  n_unique_configs: number;
  mean_fitness: number | null;
  hit_rate: number;
  last_seen: string;
}

export interface LeverageResponse {
  n_runs: number;
  n_measurements: number;
  n_unique_queries: number;
  per_query: PerQueryRow[];
}

/** One page of diagnostic-run records, newest first. */
export interface DiagnosticRunListResponse {
  n: number;
  runs: DiagnosticRunRecord[];
}
