export type {
  AbilityReading,
  ArmOutcome,
  ArchiveReport,
  ActiveSessionResponse,
  CampaignListResponse,
  CampaignRunsWith,
  CampaignSummary,
  RunsWithParam,
  VendorModels,
  RankedEdit,
  EffectProvenance,
  ConfigKeys,
  EditSpread,
  SubjectReading,
  WinnerChainPoint,
  Comparability,
  ArmReplicate,
  FactorCell,
  FactorGridReading,
  FactorLevel,
  FactorReading,
  EvidenceVariance,
  EvidencePower,
  OrderConfound,
  MetricSpec,
  PairwiseComparison,
  CloseSpend,
  RunStanding,
  LivesReading,
  MachineNotice,
  ProducerReading,
  RunAdmission,
  MetricReading,
  HeadToHead,
  HeadToHeadRow,
  Evidence,
  CommandAcceptedBody,
  NodeSearchNarrowing,
  ParamIntent,
  CycleHop,
  BandedValue,
  BenchPassProgress,
  BenchReading,
  BenchScore,
  CycleListEntry,
  LineStanding,
  CyclesResponse,
  DatasetItem,
  DatasetPipelineResponse,
  NestedPipelineRef,
  Cell,
  CellCandidate,
  CellRow,
  CellsResponse,
  CellSpan,
  DegradationHealth,
  FileContentResponse,
  FileEntry,
  FilesResponse,
  BackendWarning,
  CatchUpLogEntry,
  ServedBackpressure,
  DashboardError,
  LineageDivergence,
  ArmNode,
  CourseNode,
  ForkStamp,
  LensShift,
  MainLineStep,
  ArmReading,
  ArmPanel,
  ArmSpend,
  ArmAbility,
  ArmElection,
  ArmPointer,
  SampleWalk,
  ServedDashboard,
  WarmingDashboard,
  LoopWarning,
  NodeBlock,
  RoundAudit,
  RunLimits,
  CurrentRound,
  DashboardCandidate,
  LiftEstimate,
  MeasuredLift,
  Measurand,
  PairGuard,
  PairedReading,
  LiveCandidate,
  ModelCapability,
  NodeConfigParam,
  NodeOutputSchema,
  NodeReach,
  OptimizerFact,
  OptimizerLimit,
  OptimizerPipelineResponse,
  StartPrompt,
  PipelineView,
  PipelineViewEdge,
  PipelineViewNode,
  LineRate,
  OverlapReading,
  RoundAdvance,
  PanelPrecision,
  RayItem,
  RayResponse,
  ProjectionEnvelope,
  ActivityItem,
  ActivityState,
  ActivityDecision,
  DecisionAction,
  DashboardSample,
  RoundResult,
  ServedRound,
  ScoreboardRow,
  ScoredCandidate,
  SheetRow,
  ValidationFailure,
  VerifyPassProgress,
  VerifyReading,
  SpendBucket,
  SpendRollup,
  PrefixReading,
  KindSpend,
  MeteredSpend,
  LifetimeSpend,
  ForkRemainder,
  ActivityBucket,
  ActivityResponse,
  BackendHealthResponse,
  HealthResponse,
  LifecycleFilter,
  BackendResponse,
  CampaignPipelineResponse,
  CampaignStorageResponse,
  ConfigCoupling,
  ConfigEstimandGroup,
  ConfigKnob,
  ConfigMapResponse,
  ConnectedAccount,
  DatasetIndexEntry,
  DatasetIndexResponse,
  DatasetStorageEntry,
  DatasetStorageResponse,
  ForkPreviewResponse,
  MachineHolder,
  MachineRefusal,
  MachineStatusResponse,
  KnobRow,
  ManifestNodeOverlay,
  NodeKnobs,
  OptimizerEntry,
  OptimizerKnobsResponse,
  OptimizerRoster,
  MeResponse,
  OriginEntry,
  OriginListResponse,
  QuotaStatus,
  UserSettings,
  WorkspaceStorageEntry,
  WorkspaceStorageResponse,
  CheckinReopenResponse,
  DatasetReplaced,
  DraftCampaignWire,
  DraftDependency,
  FieldGap,
  OptimizationOverrides,
  OriginLastResolution,
  OriginQuestion,
  OriginReadiness,
  OriginResolution,
  RaisedCommand,
  ResolveOriginResponse,
  StartCheckinResponse,
} from "./types.generated";

import type {
  ArmNode,
  CampaignPipelineResponse,
  CellsResponse,
  CourseNode,
  CycleListEntry,
  DraftCampaignWire,
  EditDraftPatch,
  ServedDashboard,
} from "./types.generated";

// The two kinds strictly alternate, each typed to hold only the other: narrow on `kind` once.
export type LineageNode = CourseNode | ArmNode;

export type DraftPatch = Partial<EditDraftPatch>;

export type Provenance = DraftCampaignWire["field_provenance"][string];

// served: `domain/cells.py::HeatmapScope`
export type HardSamplesScope = CellsResponse["scope"];

export type MintKind = CycleListEntry["mint_kind"];

export type MeasuredUnit = ServedDashboard["measured_unit"];

// provider → model → capability; the provider key is the node's own `provider` value, "" for none.
export type CapabilityMenu = CampaignPipelineResponse["model_capabilities"];

